// Code generated by ent, DO NOT EDIT.

package federatedidentity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"sso.internal/sso/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldUserID, v))
}

// IdentityProviderID applies equality check predicate on the "identity_provider_id" field. It's identical to IdentityProviderIDEQ.
func IdentityProviderID(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldIdentityProviderID, v))
}

// ExternalSubject applies equality check predicate on the "external_subject" field. It's identical to ExternalSubjectEQ.
func ExternalSubject(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldExternalSubject, v))
}

// LinkedAt applies equality check predicate on the "linked_at" field. It's identical to LinkedAtEQ.
func LinkedAt(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldLinkedAt, v))
}

// LastLoginAt applies equality check predicate on the "last_login_at" field. It's identical to LastLoginAtEQ.
func LastLoginAt(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldLastLoginAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContainsFold(FieldUserID, v))
}

// IdentityProviderIDEQ applies the EQ predicate on the "identity_provider_id" field.
func IdentityProviderIDEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldIdentityProviderID, v))
}

// IdentityProviderIDNEQ applies the NEQ predicate on the "identity_provider_id" field.
func IdentityProviderIDNEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldIdentityProviderID, v))
}

// IdentityProviderIDIn applies the In predicate on the "identity_provider_id" field.
func IdentityProviderIDIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldIdentityProviderID, vs...))
}

// IdentityProviderIDNotIn applies the NotIn predicate on the "identity_provider_id" field.
func IdentityProviderIDNotIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldIdentityProviderID, vs...))
}

// IdentityProviderIDGT applies the GT predicate on the "identity_provider_id" field.
func IdentityProviderIDGT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldIdentityProviderID, v))
}

// IdentityProviderIDGTE applies the GTE predicate on the "identity_provider_id" field.
func IdentityProviderIDGTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldIdentityProviderID, v))
}

// IdentityProviderIDLT applies the LT predicate on the "identity_provider_id" field.
func IdentityProviderIDLT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldIdentityProviderID, v))
}

// IdentityProviderIDLTE applies the LTE predicate on the "identity_provider_id" field.
func IdentityProviderIDLTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldIdentityProviderID, v))
}

// IdentityProviderIDContains applies the Contains predicate on the "identity_provider_id" field.
func IdentityProviderIDContains(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContains(FieldIdentityProviderID, v))
}

// IdentityProviderIDHasPrefix applies the HasPrefix predicate on the "identity_provider_id" field.
func IdentityProviderIDHasPrefix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasPrefix(FieldIdentityProviderID, v))
}

// IdentityProviderIDHasSuffix applies the HasSuffix predicate on the "identity_provider_id" field.
func IdentityProviderIDHasSuffix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasSuffix(FieldIdentityProviderID, v))
}

// IdentityProviderIDEqualFold applies the EqualFold predicate on the "identity_provider_id" field.
func IdentityProviderIDEqualFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEqualFold(FieldIdentityProviderID, v))
}

// IdentityProviderIDContainsFold applies the ContainsFold predicate on the "identity_provider_id" field.
func IdentityProviderIDContainsFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContainsFold(FieldIdentityProviderID, v))
}

// ExternalSubjectEQ applies the EQ predicate on the "external_subject" field.
func ExternalSubjectEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldExternalSubject, v))
}

// ExternalSubjectNEQ applies the NEQ predicate on the "external_subject" field.
func ExternalSubjectNEQ(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldExternalSubject, v))
}

// ExternalSubjectIn applies the In predicate on the "external_subject" field.
func ExternalSubjectIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldExternalSubject, vs...))
}

// ExternalSubjectNotIn applies the NotIn predicate on the "external_subject" field.
func ExternalSubjectNotIn(vs ...string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldExternalSubject, vs...))
}

// ExternalSubjectGT applies the GT predicate on the "external_subject" field.
func ExternalSubjectGT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldExternalSubject, v))
}

// ExternalSubjectGTE applies the GTE predicate on the "external_subject" field.
func ExternalSubjectGTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldExternalSubject, v))
}

// ExternalSubjectLT applies the LT predicate on the "external_subject" field.
func ExternalSubjectLT(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldExternalSubject, v))
}

// ExternalSubjectLTE applies the LTE predicate on the "external_subject" field.
func ExternalSubjectLTE(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldExternalSubject, v))
}

// ExternalSubjectContains applies the Contains predicate on the "external_subject" field.
func ExternalSubjectContains(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContains(FieldExternalSubject, v))
}

// ExternalSubjectHasPrefix applies the HasPrefix predicate on the "external_subject" field.
func ExternalSubjectHasPrefix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasPrefix(FieldExternalSubject, v))
}

// ExternalSubjectHasSuffix applies the HasSuffix predicate on the "external_subject" field.
func ExternalSubjectHasSuffix(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldHasSuffix(FieldExternalSubject, v))
}

// ExternalSubjectEqualFold applies the EqualFold predicate on the "external_subject" field.
func ExternalSubjectEqualFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEqualFold(FieldExternalSubject, v))
}

// ExternalSubjectContainsFold applies the ContainsFold predicate on the "external_subject" field.
func ExternalSubjectContainsFold(v string) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldContainsFold(FieldExternalSubject, v))
}

// LinkedAtEQ applies the EQ predicate on the "linked_at" field.
func LinkedAtEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldLinkedAt, v))
}

// LinkedAtNEQ applies the NEQ predicate on the "linked_at" field.
func LinkedAtNEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldLinkedAt, v))
}

// LinkedAtIn applies the In predicate on the "linked_at" field.
func LinkedAtIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldLinkedAt, vs...))
}

// LinkedAtNotIn applies the NotIn predicate on the "linked_at" field.
func LinkedAtNotIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldLinkedAt, vs...))
}

// LinkedAtGT applies the GT predicate on the "linked_at" field.
func LinkedAtGT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldLinkedAt, v))
}

// LinkedAtGTE applies the GTE predicate on the "linked_at" field.
func LinkedAtGTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldLinkedAt, v))
}

// LinkedAtLT applies the LT predicate on the "linked_at" field.
func LinkedAtLT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldLinkedAt, v))
}

// LinkedAtLTE applies the LTE predicate on the "linked_at" field.
func LinkedAtLTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldLinkedAt, v))
}

// LastLoginAtEQ applies the EQ predicate on the "last_login_at" field.
func LastLoginAtEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldEQ(FieldLastLoginAt, v))
}

// LastLoginAtNEQ applies the NEQ predicate on the "last_login_at" field.
func LastLoginAtNEQ(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNEQ(FieldLastLoginAt, v))
}

// LastLoginAtIn applies the In predicate on the "last_login_at" field.
func LastLoginAtIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIn(FieldLastLoginAt, vs...))
}

// LastLoginAtNotIn applies the NotIn predicate on the "last_login_at" field.
func LastLoginAtNotIn(vs ...time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotIn(FieldLastLoginAt, vs...))
}

// LastLoginAtGT applies the GT predicate on the "last_login_at" field.
func LastLoginAtGT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGT(FieldLastLoginAt, v))
}

// LastLoginAtGTE applies the GTE predicate on the "last_login_at" field.
func LastLoginAtGTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldGTE(FieldLastLoginAt, v))
}

// LastLoginAtLT applies the LT predicate on the "last_login_at" field.
func LastLoginAtLT(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLT(FieldLastLoginAt, v))
}

// LastLoginAtLTE applies the LTE predicate on the "last_login_at" field.
func LastLoginAtLTE(v time.Time) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldLTE(FieldLastLoginAt, v))
}

// LastLoginAtIsNil applies the IsNil predicate on the "last_login_at" field.
func LastLoginAtIsNil() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldIsNull(FieldLastLoginAt))
}

// LastLoginAtNotNil applies the NotNil predicate on the "last_login_at" field.
func LastLoginAtNotNil() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.FieldNotNull(FieldLastLoginAt))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIdentityProvider applies the HasEdge predicate on the "identity_provider" edge.
func HasIdentityProvider() predicate.FederatedIdentity {
	return predicate.FederatedIdentity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IdentityProviderTable, IdentityProviderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIdentityProviderWith applies the HasEdge predicate on the "identity_provider" edge with a given conditions (other predicates).
func HasIdentityProviderWith(preds ...predicate.IdentityProvider) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(func(s *sql.Selector) {
		step := newIdentityProviderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FederatedIdentity) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FederatedIdentity) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FederatedIdentity) predicate.FederatedIdentity {
	return predicate.FederatedIdentity(sql.NotPredicates(p))
}
