// Code generated by ent, DO NOT EDIT.

package clientrole

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"sso.internal/sso/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldContainsFold(FieldID, id))
}

// ClientAppID applies equality check predicate on the "client_app_id" field. It's identical to ClientAppIDEQ.
func ClientAppID(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldClientAppID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldRoleID, v))
}

// GrantedAt applies equality check predicate on the "granted_at" field. It's identical to GrantedAtEQ.
func GrantedAt(v time.Time) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldGrantedAt, v))
}

// GrantedBy applies equality check predicate on the "granted_by" field. It's identical to GrantedByEQ.
func GrantedBy(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldGrantedBy, v))
}

// ClientAppIDEQ applies the EQ predicate on the "client_app_id" field.
func ClientAppIDEQ(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldClientAppID, v))
}

// ClientAppIDNEQ applies the NEQ predicate on the "client_app_id" field.
func ClientAppIDNEQ(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNEQ(FieldClientAppID, v))
}

// ClientAppIDIn applies the In predicate on the "client_app_id" field.
func ClientAppIDIn(vs ...string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldIn(FieldClientAppID, vs...))
}

// ClientAppIDNotIn applies the NotIn predicate on the "client_app_id" field.
func ClientAppIDNotIn(vs ...string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNotIn(FieldClientAppID, vs...))
}

// ClientAppIDGT applies the GT predicate on the "client_app_id" field.
func ClientAppIDGT(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGT(FieldClientAppID, v))
}

// ClientAppIDGTE applies the GTE predicate on the "client_app_id" field.
func ClientAppIDGTE(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGTE(FieldClientAppID, v))
}

// ClientAppIDLT applies the LT predicate on the "client_app_id" field.
func ClientAppIDLT(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLT(FieldClientAppID, v))
}

// ClientAppIDLTE applies the LTE predicate on the "client_app_id" field.
func ClientAppIDLTE(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLTE(FieldClientAppID, v))
}

// ClientAppIDContains applies the Contains predicate on the "client_app_id" field.
func ClientAppIDContains(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldContains(FieldClientAppID, v))
}

// ClientAppIDHasPrefix applies the HasPrefix predicate on the "client_app_id" field.
func ClientAppIDHasPrefix(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldHasPrefix(FieldClientAppID, v))
}

// ClientAppIDHasSuffix applies the HasSuffix predicate on the "client_app_id" field.
func ClientAppIDHasSuffix(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldHasSuffix(FieldClientAppID, v))
}

// ClientAppIDEqualFold applies the EqualFold predicate on the "client_app_id" field.
func ClientAppIDEqualFold(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEqualFold(FieldClientAppID, v))
}

// ClientAppIDContainsFold applies the ContainsFold predicate on the "client_app_id" field.
func ClientAppIDContainsFold(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldContainsFold(FieldClientAppID, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDContains applies the Contains predicate on the "role_id" field.
func RoleIDContains(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldContains(FieldRoleID, v))
}

// RoleIDHasPrefix applies the HasPrefix predicate on the "role_id" field.
func RoleIDHasPrefix(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldHasPrefix(FieldRoleID, v))
}

// RoleIDHasSuffix applies the HasSuffix predicate on the "role_id" field.
func RoleIDHasSuffix(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldHasSuffix(FieldRoleID, v))
}

// RoleIDEqualFold applies the EqualFold predicate on the "role_id" field.
func RoleIDEqualFold(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEqualFold(FieldRoleID, v))
}

// RoleIDContainsFold applies the ContainsFold predicate on the "role_id" field.
func RoleIDContainsFold(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldContainsFold(FieldRoleID, v))
}

// GrantedAtEQ applies the EQ predicate on the "granted_at" field.
func GrantedAtEQ(v time.Time) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldGrantedAt, v))
}

// GrantedAtNEQ applies the NEQ predicate on the "granted_at" field.
func GrantedAtNEQ(v time.Time) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNEQ(FieldGrantedAt, v))
}

// GrantedAtIn applies the In predicate on the "granted_at" field.
func GrantedAtIn(vs ...time.Time) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldIn(FieldGrantedAt, vs...))
}

// GrantedAtNotIn applies the NotIn predicate on the "granted_at" field.
func GrantedAtNotIn(vs ...time.Time) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNotIn(FieldGrantedAt, vs...))
}

// GrantedAtGT applies the GT predicate on the "granted_at" field.
func GrantedAtGT(v time.Time) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGT(FieldGrantedAt, v))
}

// GrantedAtGTE applies the GTE predicate on the "granted_at" field.
func GrantedAtGTE(v time.Time) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGTE(FieldGrantedAt, v))
}

// GrantedAtLT applies the LT predicate on the "granted_at" field.
func GrantedAtLT(v time.Time) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLT(FieldGrantedAt, v))
}

// GrantedAtLTE applies the LTE predicate on the "granted_at" field.
func GrantedAtLTE(v time.Time) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLTE(FieldGrantedAt, v))
}

// GrantedByEQ applies the EQ predicate on the "granted_by" field.
func GrantedByEQ(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEQ(FieldGrantedBy, v))
}

// GrantedByNEQ applies the NEQ predicate on the "granted_by" field.
func GrantedByNEQ(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNEQ(FieldGrantedBy, v))
}

// GrantedByIn applies the In predicate on the "granted_by" field.
func GrantedByIn(vs ...string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldIn(FieldGrantedBy, vs...))
}

// GrantedByNotIn applies the NotIn predicate on the "granted_by" field.
func GrantedByNotIn(vs ...string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNotIn(FieldGrantedBy, vs...))
}

// GrantedByGT applies the GT predicate on the "granted_by" field.
func GrantedByGT(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGT(FieldGrantedBy, v))
}

// GrantedByGTE applies the GTE predicate on the "granted_by" field.
func GrantedByGTE(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldGTE(FieldGrantedBy, v))
}

// GrantedByLT applies the LT predicate on the "granted_by" field.
func GrantedByLT(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLT(FieldGrantedBy, v))
}

// GrantedByLTE applies the LTE predicate on the "granted_by" field.
func GrantedByLTE(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldLTE(FieldGrantedBy, v))
}

// GrantedByContains applies the Contains predicate on the "granted_by" field.
func GrantedByContains(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldContains(FieldGrantedBy, v))
}

// GrantedByHasPrefix applies the HasPrefix predicate on the "granted_by" field.
func GrantedByHasPrefix(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldHasPrefix(FieldGrantedBy, v))
}

// GrantedByHasSuffix applies the HasSuffix predicate on the "granted_by" field.
func GrantedByHasSuffix(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldHasSuffix(FieldGrantedBy, v))
}

// GrantedByIsNil applies the IsNil predicate on the "granted_by" field.
func GrantedByIsNil() predicate.ClientRole {
	return predicate.ClientRole(sql.FieldIsNull(FieldGrantedBy))
}

// GrantedByNotNil applies the NotNil predicate on the "granted_by" field.
func GrantedByNotNil() predicate.ClientRole {
	return predicate.ClientRole(sql.FieldNotNull(FieldGrantedBy))
}

// GrantedByEqualFold applies the EqualFold predicate on the "granted_by" field.
func GrantedByEqualFold(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldEqualFold(FieldGrantedBy, v))
}

// GrantedByContainsFold applies the ContainsFold predicate on the "granted_by" field.
func GrantedByContainsFold(v string) predicate.ClientRole {
	return predicate.ClientRole(sql.FieldContainsFold(FieldGrantedBy, v))
}

// HasClientApp applies the HasEdge predicate on the "client_app" edge.
func HasClientApp() predicate.ClientRole {
	return predicate.ClientRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ClientAppTable, ClientAppColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientAppWith applies the HasEdge predicate on the "client_app" edge with a given conditions (other predicates).
func HasClientAppWith(preds ...predicate.ClientApp) predicate.ClientRole {
	return predicate.ClientRole(func(s *sql.Selector) {
		step := newClientAppStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.ClientRole {
	return predicate.ClientRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.ClientRole {
	return predicate.ClientRole(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClientRole) predicate.ClientRole {
	return predicate.ClientRole(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClientRole) predicate.ClientRole {
	return predicate.ClientRole(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClientRole) predicate.ClientRole {
	return predicate.ClientRole(sql.NotPredicates(p))
}
