// Code generated by ent, DO NOT EDIT.

package token

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"sso.internal/sso/ent/predicate"
	"sso.internal/sso/ent/schema"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Token {
	return predicate.Token(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Token {
	return predicate.Token(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Token {
	return predicate.Token(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Token {
	return predicate.Token(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Token {
	return predicate.Token(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Token {
	return predicate.Token(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Token {
	return predicate.Token(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Token {
	return predicate.Token(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Token {
	return predicate.Token(sql.FieldContainsFold(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldSessionID, v))
}

// ClientRefID applies equality check predicate on the "client_ref_id" field. It's identical to ClientRefIDEQ.
func ClientRefID(v string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldClientRefID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldEQ(FieldType, vc))
}

// Jti applies equality check predicate on the "jti" field. It's identical to JtiEQ.
func Jti(v string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldJti, v))
}

// IssuedAt applies equality check predicate on the "issued_at" field. It's identical to IssuedAtEQ.
func IssuedAt(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldIssuedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldExpiresAt, v))
}

// Revoked applies equality check predicate on the "revoked" field. It's identical to RevokedEQ.
func Revoked(v bool) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldRevoked, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.Token {
	return predicate.Token(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.Token {
	return predicate.Token(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.Token {
	return predicate.Token(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.Token {
	return predicate.Token(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.Token {
	return predicate.Token(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.Token {
	return predicate.Token(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.Token {
	return predicate.Token(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.Token {
	return predicate.Token(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.Token {
	return predicate.Token(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.Token {
	return predicate.Token(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.Token {
	return predicate.Token(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.Token {
	return predicate.Token(sql.FieldContainsFold(FieldSessionID, v))
}

// ClientRefIDEQ applies the EQ predicate on the "client_ref_id" field.
func ClientRefIDEQ(v string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldClientRefID, v))
}

// ClientRefIDNEQ applies the NEQ predicate on the "client_ref_id" field.
func ClientRefIDNEQ(v string) predicate.Token {
	return predicate.Token(sql.FieldNEQ(FieldClientRefID, v))
}

// ClientRefIDIn applies the In predicate on the "client_ref_id" field.
func ClientRefIDIn(vs ...string) predicate.Token {
	return predicate.Token(sql.FieldIn(FieldClientRefID, vs...))
}

// ClientRefIDNotIn applies the NotIn predicate on the "client_ref_id" field.
func ClientRefIDNotIn(vs ...string) predicate.Token {
	return predicate.Token(sql.FieldNotIn(FieldClientRefID, vs...))
}

// ClientRefIDGT applies the GT predicate on the "client_ref_id" field.
func ClientRefIDGT(v string) predicate.Token {
	return predicate.Token(sql.FieldGT(FieldClientRefID, v))
}

// ClientRefIDGTE applies the GTE predicate on the "client_ref_id" field.
func ClientRefIDGTE(v string) predicate.Token {
	return predicate.Token(sql.FieldGTE(FieldClientRefID, v))
}

// ClientRefIDLT applies the LT predicate on the "client_ref_id" field.
func ClientRefIDLT(v string) predicate.Token {
	return predicate.Token(sql.FieldLT(FieldClientRefID, v))
}

// ClientRefIDLTE applies the LTE predicate on the "client_ref_id" field.
func ClientRefIDLTE(v string) predicate.Token {
	return predicate.Token(sql.FieldLTE(FieldClientRefID, v))
}

// ClientRefIDContains applies the Contains predicate on the "client_ref_id" field.
func ClientRefIDContains(v string) predicate.Token {
	return predicate.Token(sql.FieldContains(FieldClientRefID, v))
}

// ClientRefIDHasPrefix applies the HasPrefix predicate on the "client_ref_id" field.
func ClientRefIDHasPrefix(v string) predicate.Token {
	return predicate.Token(sql.FieldHasPrefix(FieldClientRefID, v))
}

// ClientRefIDHasSuffix applies the HasSuffix predicate on the "client_ref_id" field.
func ClientRefIDHasSuffix(v string) predicate.Token {
	return predicate.Token(sql.FieldHasSuffix(FieldClientRefID, v))
}

// ClientRefIDEqualFold applies the EqualFold predicate on the "client_ref_id" field.
func ClientRefIDEqualFold(v string) predicate.Token {
	return predicate.Token(sql.FieldEqualFold(FieldClientRefID, v))
}

// ClientRefIDContainsFold applies the ContainsFold predicate on the "client_ref_id" field.
func ClientRefIDContainsFold(v string) predicate.Token {
	return predicate.Token(sql.FieldContainsFold(FieldClientRefID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldEQ(FieldType, vc))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldNEQ(FieldType, vc))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...schema.TokenType) predicate.Token {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Token(sql.FieldIn(FieldType, v...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...schema.TokenType) predicate.Token {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = string(vs[i])
	}
	return predicate.Token(sql.FieldNotIn(FieldType, v...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldGT(FieldType, vc))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldGTE(FieldType, vc))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldLT(FieldType, vc))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldLTE(FieldType, vc))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldContains(FieldType, vc))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldHasPrefix(FieldType, vc))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldHasSuffix(FieldType, vc))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldEqualFold(FieldType, vc))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v schema.TokenType) predicate.Token {
	vc := string(v)
	return predicate.Token(sql.FieldContainsFold(FieldType, vc))
}

// JtiEQ applies the EQ predicate on the "jti" field.
func JtiEQ(v string) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldJti, v))
}

// JtiNEQ applies the NEQ predicate on the "jti" field.
func JtiNEQ(v string) predicate.Token {
	return predicate.Token(sql.FieldNEQ(FieldJti, v))
}

// JtiIn applies the In predicate on the "jti" field.
func JtiIn(vs ...string) predicate.Token {
	return predicate.Token(sql.FieldIn(FieldJti, vs...))
}

// JtiNotIn applies the NotIn predicate on the "jti" field.
func JtiNotIn(vs ...string) predicate.Token {
	return predicate.Token(sql.FieldNotIn(FieldJti, vs...))
}

// JtiGT applies the GT predicate on the "jti" field.
func JtiGT(v string) predicate.Token {
	return predicate.Token(sql.FieldGT(FieldJti, v))
}

// JtiGTE applies the GTE predicate on the "jti" field.
func JtiGTE(v string) predicate.Token {
	return predicate.Token(sql.FieldGTE(FieldJti, v))
}

// JtiLT applies the LT predicate on the "jti" field.
func JtiLT(v string) predicate.Token {
	return predicate.Token(sql.FieldLT(FieldJti, v))
}

// JtiLTE applies the LTE predicate on the "jti" field.
func JtiLTE(v string) predicate.Token {
	return predicate.Token(sql.FieldLTE(FieldJti, v))
}

// JtiContains applies the Contains predicate on the "jti" field.
func JtiContains(v string) predicate.Token {
	return predicate.Token(sql.FieldContains(FieldJti, v))
}

// JtiHasPrefix applies the HasPrefix predicate on the "jti" field.
func JtiHasPrefix(v string) predicate.Token {
	return predicate.Token(sql.FieldHasPrefix(FieldJti, v))
}

// JtiHasSuffix applies the HasSuffix predicate on the "jti" field.
func JtiHasSuffix(v string) predicate.Token {
	return predicate.Token(sql.FieldHasSuffix(FieldJti, v))
}

// JtiEqualFold applies the EqualFold predicate on the "jti" field.
func JtiEqualFold(v string) predicate.Token {
	return predicate.Token(sql.FieldEqualFold(FieldJti, v))
}

// JtiContainsFold applies the ContainsFold predicate on the "jti" field.
func JtiContainsFold(v string) predicate.Token {
	return predicate.Token(sql.FieldContainsFold(FieldJti, v))
}

// IssuedAtEQ applies the EQ predicate on the "issued_at" field.
func IssuedAtEQ(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldIssuedAt, v))
}

// IssuedAtNEQ applies the NEQ predicate on the "issued_at" field.
func IssuedAtNEQ(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldNEQ(FieldIssuedAt, v))
}

// IssuedAtIn applies the In predicate on the "issued_at" field.
func IssuedAtIn(vs ...time.Time) predicate.Token {
	return predicate.Token(sql.FieldIn(FieldIssuedAt, vs...))
}

// IssuedAtNotIn applies the NotIn predicate on the "issued_at" field.
func IssuedAtNotIn(vs ...time.Time) predicate.Token {
	return predicate.Token(sql.FieldNotIn(FieldIssuedAt, vs...))
}

// IssuedAtGT applies the GT predicate on the "issued_at" field.
func IssuedAtGT(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldGT(FieldIssuedAt, v))
}

// IssuedAtGTE applies the GTE predicate on the "issued_at" field.
func IssuedAtGTE(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldGTE(FieldIssuedAt, v))
}

// IssuedAtLT applies the LT predicate on the "issued_at" field.
func IssuedAtLT(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldLT(FieldIssuedAt, v))
}

// IssuedAtLTE applies the LTE predicate on the "issued_at" field.
func IssuedAtLTE(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldLTE(FieldIssuedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Token {
	return predicate.Token(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Token {
	return predicate.Token(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Token {
	return predicate.Token(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedEQ applies the EQ predicate on the "revoked" field.
func RevokedEQ(v bool) predicate.Token {
	return predicate.Token(sql.FieldEQ(FieldRevoked, v))
}

// RevokedNEQ applies the NEQ predicate on the "revoked" field.
func RevokedNEQ(v bool) predicate.Token {
	return predicate.Token(sql.FieldNEQ(FieldRevoked, v))
}

// ScopesIsNil applies the IsNil predicate on the "scopes" field.
func ScopesIsNil() predicate.Token {
	return predicate.Token(sql.FieldIsNull(FieldScopes))
}

// ScopesNotNil applies the NotNil predicate on the "scopes" field.
func ScopesNotNil() predicate.Token {
	return predicate.Token(sql.FieldNotNull(FieldScopes))
}

// HasSession applies the HasEdge predicate on the "session" edge.
func HasSession() predicate.Token {
	return predicate.Token(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SessionTable, SessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSessionWith applies the HasEdge predicate on the "session" edge with a given conditions (other predicates).
func HasSessionWith(preds ...predicate.Session) predicate.Token {
	return predicate.Token(func(s *sql.Selector) {
		step := newSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClientApp applies the HasEdge predicate on the "client_app" edge.
func HasClientApp() predicate.Token {
	return predicate.Token(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ClientAppTable, ClientAppColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientAppWith applies the HasEdge predicate on the "client_app" edge with a given conditions (other predicates).
func HasClientAppWith(preds ...predicate.ClientApp) predicate.Token {
	return predicate.Token(func(s *sql.Selector) {
		step := newClientAppStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Token) predicate.Token {
	return predicate.Token(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Token) predicate.Token {
	return predicate.Token(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Token) predicate.Token {
	return predicate.Token(sql.NotPredicates(p))
}
