// Code generated by ent, DO NOT EDIT.

package signingkey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"sso.internal/sso/ent/schema"
)

const (
	// Label holds the string label denoting the signingkey type in the database.
	Label = "signing_key"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRealmID holds the string denoting the realm_id field in the database.
	FieldRealmID = "realm_id"
	// FieldKeyType holds the string denoting the key_type field in the database.
	FieldKeyType = "key_type"
	// FieldPurpose holds the string denoting the purpose field in the database.
	FieldPurpose = "purpose"
	// FieldKmsKeyReference holds the string denoting the kms_key_reference field in the database.
	FieldKmsKeyReference = "kms_key_reference"
	// FieldKmsBackend holds the string denoting the kms_backend field in the database.
	FieldKmsBackend = "kms_backend"
	// FieldPublicKey holds the string denoting the public_key field in the database.
	FieldPublicKey = "public_key"
	// FieldKid holds the string denoting the kid field in the database.
	FieldKid = "kid"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRetiredAt holds the string denoting the retired_at field in the database.
	FieldRetiredAt = "retired_at"
	// EdgeRealm holds the string denoting the realm edge name in mutations.
	EdgeRealm = "realm"
	// EdgeRotationLogs holds the string denoting the rotation_logs edge name in mutations.
	EdgeRotationLogs = "rotation_logs"
	// Table holds the table name of the signingkey in the database.
	Table = "signing_keys"
	// RealmTable is the table that holds the realm relation/edge.
	RealmTable = "signing_keys"
	// RealmInverseTable is the table name for the Realm entity.
	// It exists in this package in order to avoid circular dependency with the "realm" package.
	RealmInverseTable = "realms"
	// RealmColumn is the table column denoting the realm relation/edge.
	RealmColumn = "realm_id"
	// RotationLogsTable is the table that holds the rotation_logs relation/edge.
	RotationLogsTable = "key_rotation_logs"
	// RotationLogsInverseTable is the table name for the KeyRotationLog entity.
	// It exists in this package in order to avoid circular dependency with the "keyrotationlog" package.
	RotationLogsInverseTable = "key_rotation_logs"
	// RotationLogsColumn is the table column denoting the rotation_logs relation/edge.
	RotationLogsColumn = "signing_key_id"
)

// Columns holds all SQL columns for signingkey fields.
var Columns = []string{
	FieldID,
	FieldRealmID,
	FieldKeyType,
	FieldPurpose,
	FieldKmsKeyReference,
	FieldKmsBackend,
	FieldPublicKey,
	FieldKid,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRetiredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RealmIDValidator is a validator for the "realm_id" field. It is called by the builders before save.
	RealmIDValidator func(string) error
	// KmsKeyReferenceValidator is a validator for the "kms_key_reference" field. It is called by the builders before save.
	KmsKeyReferenceValidator func(string) error
	// KmsBackendValidator is a validator for the "kms_backend" field. It is called by the builders before save.
	KmsBackendValidator func(string) error
	// KidValidator is a validator for the "kid" field. It is called by the builders before save.
	KidValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus schema.SigningKeyStatus
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the SigningKey queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRealmID orders the results by the realm_id field.
func ByRealmID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealmID, opts...).ToFunc()
}

// ByKeyType orders the results by the key_type field.
func ByKeyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeyType, opts...).ToFunc()
}

// ByPurpose orders the results by the purpose field.
func ByPurpose(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurpose, opts...).ToFunc()
}

// ByKmsKeyReference orders the results by the kms_key_reference field.
func ByKmsKeyReference(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKmsKeyReference, opts...).ToFunc()
}

// ByKmsBackend orders the results by the kms_backend field.
func ByKmsBackend(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKmsBackend, opts...).ToFunc()
}

// ByPublicKey orders the results by the public_key field.
func ByPublicKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicKey, opts...).ToFunc()
}

// ByKid orders the results by the kid field.
func ByKid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKid, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRetiredAt orders the results by the retired_at field.
func ByRetiredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetiredAt, opts...).ToFunc()
}

// ByRealmField orders the results by realm field.
func ByRealmField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRealmStep(), sql.OrderByField(field, opts...))
	}
}

// ByRotationLogsCount orders the results by rotation_logs count.
func ByRotationLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRotationLogsStep(), opts...)
	}
}

// ByRotationLogs orders the results by rotation_logs terms.
func ByRotationLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRotationLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRealmStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RealmInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RealmTable, RealmColumn),
	)
}
func newRotationLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RotationLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RotationLogsTable, RotationLogsColumn),
	)
}
