// Code generated by ent, DO NOT EDIT.

package identityprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"sso.internal/sso/ent/schema"
)

const (
	// Label holds the string label denoting the identityprovider type in the database.
	Label = "identity_provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRealmID holds the string denoting the realm_id field in the database.
	FieldRealmID = "realm_id"
	// FieldManagedBy holds the string denoting the managed_by field in the database.
	FieldManagedBy = "managed_by"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldIssuerURL holds the string denoting the issuer_url field in the database.
	FieldIssuerURL = "issuer_url"
	// FieldClientID holds the string denoting the client_id field in the database.
	FieldClientID = "client_id"
	// FieldClientSecretHash holds the string denoting the client_secret_hash field in the database.
	FieldClientSecretHash = "client_secret_hash"
	// FieldAuthorizationEndpoint holds the string denoting the authorization_endpoint field in the database.
	FieldAuthorizationEndpoint = "authorization_endpoint"
	// FieldTokenEndpoint holds the string denoting the token_endpoint field in the database.
	FieldTokenEndpoint = "token_endpoint"
	// FieldUserinfoEndpoint holds the string denoting the userinfo_endpoint field in the database.
	FieldUserinfoEndpoint = "userinfo_endpoint"
	// FieldJwksURI holds the string denoting the jwks_uri field in the database.
	FieldJwksURI = "jwks_uri"
	// FieldScopesRequested holds the string denoting the scopes_requested field in the database.
	FieldScopesRequested = "scopes_requested"
	// FieldIdpEntityID holds the string denoting the idp_entity_id field in the database.
	FieldIdpEntityID = "idp_entity_id"
	// FieldIdpSSOURL holds the string denoting the idp_sso_url field in the database.
	FieldIdpSSOURL = "idp_sso_url"
	// FieldIdpCertificate holds the string denoting the idp_certificate field in the database.
	FieldIdpCertificate = "idp_certificate"
	// FieldAttributeMapping holds the string denoting the attribute_mapping field in the database.
	FieldAttributeMapping = "attribute_mapping"
	// FieldAutoProvisioning holds the string denoting the auto_provisioning field in the database.
	FieldAutoProvisioning = "auto_provisioning"
	// FieldDefaultRoles holds the string denoting the default_roles field in the database.
	FieldDefaultRoles = "default_roles"
	// EdgeRealm holds the string denoting the realm edge name in mutations.
	EdgeRealm = "realm"
	// EdgeFederatedIdentities holds the string denoting the federated_identities edge name in mutations.
	EdgeFederatedIdentities = "federated_identities"
	// Table holds the table name of the identityprovider in the database.
	Table = "identity_providers"
	// RealmTable is the table that holds the realm relation/edge.
	RealmTable = "identity_providers"
	// RealmInverseTable is the table name for the Realm entity.
	// It exists in this package in order to avoid circular dependency with the "realm" package.
	RealmInverseTable = "realms"
	// RealmColumn is the table column denoting the realm relation/edge.
	RealmColumn = "realm_id"
	// FederatedIdentitiesTable is the table that holds the federated_identities relation/edge.
	FederatedIdentitiesTable = "federated_identities"
	// FederatedIdentitiesInverseTable is the table name for the FederatedIdentity entity.
	// It exists in this package in order to avoid circular dependency with the "federatedidentity" package.
	FederatedIdentitiesInverseTable = "federated_identities"
	// FederatedIdentitiesColumn is the table column denoting the federated_identities relation/edge.
	FederatedIdentitiesColumn = "identity_provider_id"
)

// Columns holds all SQL columns for identityprovider fields.
var Columns = []string{
	FieldID,
	FieldRealmID,
	FieldManagedBy,
	FieldName,
	FieldProtocol,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldIssuerURL,
	FieldClientID,
	FieldClientSecretHash,
	FieldAuthorizationEndpoint,
	FieldTokenEndpoint,
	FieldUserinfoEndpoint,
	FieldJwksURI,
	FieldScopesRequested,
	FieldIdpEntityID,
	FieldIdpSSOURL,
	FieldIdpCertificate,
	FieldAttributeMapping,
	FieldAutoProvisioning,
	FieldDefaultRoles,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RealmIDValidator is a validator for the "realm_id" field. It is called by the builders before save.
	RealmIDValidator func(string) error
	// DefaultManagedBy holds the default value on creation for the "managed_by" field.
	DefaultManagedBy schema.IdentityProviderManagedBy
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus schema.IdentityProviderStatus
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAutoProvisioning holds the default value on creation for the "auto_provisioning" field.
	DefaultAutoProvisioning bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the IdentityProvider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRealmID orders the results by the realm_id field.
func ByRealmID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealmID, opts...).ToFunc()
}

// ByManagedBy orders the results by the managed_by field.
func ByManagedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagedBy, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByIssuerURL orders the results by the issuer_url field.
func ByIssuerURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuerURL, opts...).ToFunc()
}

// ByClientID orders the results by the client_id field.
func ByClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientID, opts...).ToFunc()
}

// ByClientSecretHash orders the results by the client_secret_hash field.
func ByClientSecretHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientSecretHash, opts...).ToFunc()
}

// ByAuthorizationEndpoint orders the results by the authorization_endpoint field.
func ByAuthorizationEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorizationEndpoint, opts...).ToFunc()
}

// ByTokenEndpoint orders the results by the token_endpoint field.
func ByTokenEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenEndpoint, opts...).ToFunc()
}

// ByUserinfoEndpoint orders the results by the userinfo_endpoint field.
func ByUserinfoEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserinfoEndpoint, opts...).ToFunc()
}

// ByJwksURI orders the results by the jwks_uri field.
func ByJwksURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJwksURI, opts...).ToFunc()
}

// ByIdpEntityID orders the results by the idp_entity_id field.
func ByIdpEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdpEntityID, opts...).ToFunc()
}

// ByIdpSSOURL orders the results by the idp_sso_url field.
func ByIdpSSOURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdpSSOURL, opts...).ToFunc()
}

// ByIdpCertificate orders the results by the idp_certificate field.
func ByIdpCertificate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdpCertificate, opts...).ToFunc()
}

// ByAutoProvisioning orders the results by the auto_provisioning field.
func ByAutoProvisioning(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAutoProvisioning, opts...).ToFunc()
}

// ByRealmField orders the results by realm field.
func ByRealmField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRealmStep(), sql.OrderByField(field, opts...))
	}
}

// ByFederatedIdentitiesCount orders the results by federated_identities count.
func ByFederatedIdentitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFederatedIdentitiesStep(), opts...)
	}
}

// ByFederatedIdentities orders the results by federated_identities terms.
func ByFederatedIdentities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFederatedIdentitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRealmStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RealmInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RealmTable, RealmColumn),
	)
}
func newFederatedIdentitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FederatedIdentitiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FederatedIdentitiesTable, FederatedIdentitiesColumn),
	)
}
