// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "user_id", Type: field.TypeString, Nullable: true},
		{Name: "action", Type: field.TypeString},
		{Name: "resource_type", Type: field.TypeString, Nullable: true},
		{Name: "resource_id", Type: field.TypeString, Nullable: true},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "ip_address", Type: field.TypeString, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "level", Type: field.TypeString, Default: "info"},
		{Name: "status", Type: field.TypeString, Default: "success"},
		{Name: "details", Type: field.TypeJSON, Nullable: true},
		{Name: "realm_id", Type: field.TypeString},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audit_logs_realms_audit_logs",
				Columns:    []*schema.Column{AuditLogsColumns[11]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[3], AuditLogsColumns[4]},
			},
			{
				Name:    "auditlog_user_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[1], AuditLogsColumns[5]},
			},
			{
				Name:    "auditlog_realm_id_timestamp",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[11], AuditLogsColumns[5]},
			},
		},
	}
	// ClientAppsColumns holds the columns for the "client_apps" table.
	ClientAppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "managed_by", Type: field.TypeString, Default: "ui"},
		{Name: "name", Type: field.TypeString},
		{Name: "protocol", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "owner_admin_id", Type: field.TypeString, Nullable: true},
		{Name: "client_id", Type: field.TypeString, Nullable: true},
		{Name: "client_secret_hash", Type: field.TypeString, Nullable: true},
		{Name: "client_type", Type: field.TypeString, Nullable: true},
		{Name: "redirect_uris", Type: field.TypeJSON, Nullable: true},
		{Name: "post_logout_redirect_uris", Type: field.TypeJSON, Nullable: true},
		{Name: "allowed_grant_types", Type: field.TypeJSON, Nullable: true},
		{Name: "allowed_scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "token_endpoint_auth_method", Type: field.TypeString, Nullable: true},
		{Name: "id_token_signed_alg", Type: field.TypeString, Nullable: true},
		{Name: "access_token_ttl", Type: field.TypeInt, Default: 3600},
		{Name: "refresh_token_ttl", Type: field.TypeInt, Default: 2592000},
		{Name: "id_token_ttl", Type: field.TypeInt, Default: 3600},
		{Name: "require_pkce", Type: field.TypeBool, Default: true},
		{Name: "entity_id", Type: field.TypeString, Nullable: true},
		{Name: "acs_url", Type: field.TypeString, Nullable: true},
		{Name: "slo_url", Type: field.TypeString, Nullable: true},
		{Name: "client_certificates", Type: field.TypeJSON, Nullable: true},
		{Name: "name_id_format", Type: field.TypeString, Nullable: true},
		{Name: "want_assertion_signed", Type: field.TypeBool, Default: true},
		{Name: "want_response_signed", Type: field.TypeBool, Default: false},
		{Name: "default_relay_state", Type: field.TypeString, Nullable: true},
		{Name: "attribute_mappings", Type: field.TypeJSON, Nullable: true},
		{Name: "require_consent", Type: field.TypeBool, Default: false},
		{Name: "metadata_url", Type: field.TypeString, Nullable: true},
		{Name: "realm_id", Type: field.TypeString},
	}
	// ClientAppsTable holds the schema information for the "client_apps" table.
	ClientAppsTable = &schema.Table{
		Name:       "client_apps",
		Columns:    ClientAppsColumns,
		PrimaryKey: []*schema.Column{ClientAppsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "client_apps_realms_client_apps",
				Columns:    []*schema.Column{ClientAppsColumns[33]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "clientapp_realm_id_client_id",
				Unique:  true,
				Columns: []*schema.Column{ClientAppsColumns[33], ClientAppsColumns[9]},
			},
			{
				Name:    "clientapp_realm_id_entity_id",
				Unique:  true,
				Columns: []*schema.Column{ClientAppsColumns[33], ClientAppsColumns[22]},
			},
		},
	}
	// ClientGroupsColumns holds the columns for the "client_groups" table.
	ClientGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "granted_at", Type: field.TypeTime},
		{Name: "granted_by", Type: field.TypeString, Nullable: true},
		{Name: "client_app_id", Type: field.TypeString},
		{Name: "group_id", Type: field.TypeString},
	}
	// ClientGroupsTable holds the schema information for the "client_groups" table.
	ClientGroupsTable = &schema.Table{
		Name:       "client_groups",
		Columns:    ClientGroupsColumns,
		PrimaryKey: []*schema.Column{ClientGroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "client_groups_client_apps_client_app",
				Columns:    []*schema.Column{ClientGroupsColumns[3]},
				RefColumns: []*schema.Column{ClientAppsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "client_groups_groups_group",
				Columns:    []*schema.Column{ClientGroupsColumns[4]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "clientgroup_group_id_client_app_id",
				Unique:  true,
				Columns: []*schema.Column{ClientGroupsColumns[4], ClientGroupsColumns[3]},
			},
		},
	}
	// ClientRolesColumns holds the columns for the "client_roles" table.
	ClientRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "granted_at", Type: field.TypeTime},
		{Name: "granted_by", Type: field.TypeString, Nullable: true},
		{Name: "client_app_id", Type: field.TypeString},
		{Name: "role_id", Type: field.TypeString},
	}
	// ClientRolesTable holds the schema information for the "client_roles" table.
	ClientRolesTable = &schema.Table{
		Name:       "client_roles",
		Columns:    ClientRolesColumns,
		PrimaryKey: []*schema.Column{ClientRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "client_roles_client_apps_client_app",
				Columns:    []*schema.Column{ClientRolesColumns[3]},
				RefColumns: []*schema.Column{ClientAppsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "client_roles_roles_role",
				Columns:    []*schema.Column{ClientRolesColumns[4]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "clientrole_role_id_client_app_id",
				Unique:  true,
				Columns: []*schema.Column{ClientRolesColumns[4], ClientRolesColumns[3]},
			},
		},
	}
	// ClientScopesColumns holds the columns for the "client_scopes" table.
	ClientScopesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "protocol", Type: field.TypeString, Default: "oidc"},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "claim_mappers", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "realm_id", Type: field.TypeString},
	}
	// ClientScopesTable holds the schema information for the "client_scopes" table.
	ClientScopesTable = &schema.Table{
		Name:       "client_scopes",
		Columns:    ClientScopesColumns,
		PrimaryKey: []*schema.Column{ClientScopesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "client_scopes_realms_client_scopes",
				Columns:    []*schema.Column{ClientScopesColumns[8]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "clientscope_realm_id_name",
				Unique:  true,
				Columns: []*schema.Column{ClientScopesColumns[8], ClientScopesColumns[1]},
			},
		},
	}
	// ClientScopeMappingsColumns holds the columns for the "client_scope_mappings" table.
	ClientScopeMappingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "required", Type: field.TypeBool, Default: false},
		{Name: "client_app_id", Type: field.TypeString},
		{Name: "client_scope_id", Type: field.TypeString},
	}
	// ClientScopeMappingsTable holds the schema information for the "client_scope_mappings" table.
	ClientScopeMappingsTable = &schema.Table{
		Name:       "client_scope_mappings",
		Columns:    ClientScopeMappingsColumns,
		PrimaryKey: []*schema.Column{ClientScopeMappingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "client_scope_mappings_client_apps_client_app",
				Columns:    []*schema.Column{ClientScopeMappingsColumns[2]},
				RefColumns: []*schema.Column{ClientAppsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "client_scope_mappings_client_scopes_client_scope",
				Columns:    []*schema.Column{ClientScopeMappingsColumns[3]},
				RefColumns: []*schema.Column{ClientScopesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "clientscopemapping_client_app_id_client_scope_id",
				Unique:  true,
				Columns: []*schema.Column{ClientScopeMappingsColumns[2], ClientScopeMappingsColumns[3]},
			},
		},
	}
	// ConsentsColumns holds the columns for the "consents" table.
	ConsentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "granted"},
		{Name: "granted_at", Type: field.TypeTime},
		{Name: "revoked_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "client_ref_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// ConsentsTable holds the schema information for the "consents" table.
	ConsentsTable = &schema.Table{
		Name:       "consents",
		Columns:    ConsentsColumns,
		PrimaryKey: []*schema.Column{ConsentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "consents_client_apps_consents",
				Columns:    []*schema.Column{ConsentsColumns[7]},
				RefColumns: []*schema.Column{ClientAppsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "consents_users_consents",
				Columns:    []*schema.Column{ConsentsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "consent_user_id_client_ref_id",
				Unique:  true,
				Columns: []*schema.Column{ConsentsColumns[8], ConsentsColumns[7]},
			},
		},
	}
	// FederatedIdentitiesColumns holds the columns for the "federated_identities" table.
	FederatedIdentitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "external_subject", Type: field.TypeString},
		{Name: "linked_at", Type: field.TypeTime},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "identity_provider_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// FederatedIdentitiesTable holds the schema information for the "federated_identities" table.
	FederatedIdentitiesTable = &schema.Table{
		Name:       "federated_identities",
		Columns:    FederatedIdentitiesColumns,
		PrimaryKey: []*schema.Column{FederatedIdentitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "federated_identities_identity_providers_federated_identities",
				Columns:    []*schema.Column{FederatedIdentitiesColumns[4]},
				RefColumns: []*schema.Column{IdentityProvidersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "federated_identities_users_federated_identities",
				Columns:    []*schema.Column{FederatedIdentitiesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "federatedidentity_identity_provider_id_external_subject",
				Unique:  true,
				Columns: []*schema.Column{FederatedIdentitiesColumns[4], FederatedIdentitiesColumns[1]},
			},
		},
	}
	// GroupsColumns holds the columns for the "groups" table.
	GroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "managed_by", Type: field.TypeString, Default: "ui"},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "realm_id", Type: field.TypeString},
	}
	// GroupsTable holds the schema information for the "groups" table.
	GroupsTable = &schema.Table{
		Name:       "groups",
		Columns:    GroupsColumns,
		PrimaryKey: []*schema.Column{GroupsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "groups_realms_groups",
				Columns:    []*schema.Column{GroupsColumns[7]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "group_realm_id_name",
				Unique:  true,
				Columns: []*schema.Column{GroupsColumns[7], GroupsColumns[2]},
			},
		},
	}
	// GroupClientScopesColumns holds the columns for the "group_client_scopes" table.
	GroupClientScopesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "granted_at", Type: field.TypeTime},
		{Name: "group_id", Type: field.TypeString},
		{Name: "client_scope_id", Type: field.TypeString},
	}
	// GroupClientScopesTable holds the schema information for the "group_client_scopes" table.
	GroupClientScopesTable = &schema.Table{
		Name:       "group_client_scopes",
		Columns:    GroupClientScopesColumns,
		PrimaryKey: []*schema.Column{GroupClientScopesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_client_scopes_groups_group",
				Columns:    []*schema.Column{GroupClientScopesColumns[2]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "group_client_scopes_client_scopes_client_scope",
				Columns:    []*schema.Column{GroupClientScopesColumns[3]},
				RefColumns: []*schema.Column{ClientScopesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "groupclientscope_group_id_client_scope_id",
				Unique:  true,
				Columns: []*schema.Column{GroupClientScopesColumns[2], GroupClientScopesColumns[3]},
			},
		},
	}
	// IdentityProvidersColumns holds the columns for the "identity_providers" table.
	IdentityProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "managed_by", Type: field.TypeString, Default: "ui"},
		{Name: "name", Type: field.TypeString},
		{Name: "protocol", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "issuer_url", Type: field.TypeString, Nullable: true},
		{Name: "client_id", Type: field.TypeString, Nullable: true},
		{Name: "client_secret_hash", Type: field.TypeString, Nullable: true},
		{Name: "authorization_endpoint", Type: field.TypeString, Nullable: true},
		{Name: "token_endpoint", Type: field.TypeString, Nullable: true},
		{Name: "userinfo_endpoint", Type: field.TypeString, Nullable: true},
		{Name: "jwks_uri", Type: field.TypeString, Nullable: true},
		{Name: "scopes_requested", Type: field.TypeJSON, Nullable: true},
		{Name: "idp_entity_id", Type: field.TypeString, Nullable: true},
		{Name: "idp_sso_url", Type: field.TypeString, Nullable: true},
		{Name: "idp_certificate", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "attribute_mapping", Type: field.TypeJSON, Nullable: true},
		{Name: "auto_provisioning", Type: field.TypeBool, Default: false},
		{Name: "default_roles", Type: field.TypeJSON, Nullable: true},
		{Name: "realm_id", Type: field.TypeString},
	}
	// IdentityProvidersTable holds the schema information for the "identity_providers" table.
	IdentityProvidersTable = &schema.Table{
		Name:       "identity_providers",
		Columns:    IdentityProvidersColumns,
		PrimaryKey: []*schema.Column{IdentityProvidersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "identity_providers_realms_identity_providers",
				Columns:    []*schema.Column{IdentityProvidersColumns[21]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "identityprovider_realm_id_name",
				Unique:  true,
				Columns: []*schema.Column{IdentityProvidersColumns[21], IdentityProvidersColumns[2]},
			},
		},
	}
	// InstanceSettingsColumns holds the columns for the "instance_settings" table.
	InstanceSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "managed_by", Type: field.TypeString, Default: "ui"},
		{Name: "min_password_length", Type: field.TypeInt, Default: 12},
		{Name: "password_expiry_days", Type: field.TypeInt, Default: 90},
		{Name: "session_idle_minutes", Type: field.TypeInt, Default: 30},
		{Name: "session_max_hours", Type: field.TypeInt, Default: 12},
		{Name: "lockout_threshold", Type: field.TypeInt, Default: 5},
		{Name: "lockout_duration_minutes", Type: field.TypeInt, Default: 15},
		{Name: "ip_allowlist", Type: field.TypeJSON, Nullable: true},
		{Name: "mfa_required_globally", Type: field.TypeBool, Default: false},
		{Name: "notification_email_enabled", Type: field.TypeBool, Default: false},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeString, Nullable: true},
		{Name: "realm_id", Type: field.TypeString, Unique: true},
	}
	// InstanceSettingsTable holds the schema information for the "instance_settings" table.
	InstanceSettingsTable = &schema.Table{
		Name:       "instance_settings",
		Columns:    InstanceSettingsColumns,
		PrimaryKey: []*schema.Column{InstanceSettingsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "instance_settings_realms_instance_settings",
				Columns:    []*schema.Column{InstanceSettingsColumns[13]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
	}
	// KeyRotationLogsColumns holds the columns for the "key_rotation_logs" table.
	KeyRotationLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "action", Type: field.TypeString},
		{Name: "triggered_by", Type: field.TypeString},
		{Name: "reason", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "signing_key_id", Type: field.TypeString},
	}
	// KeyRotationLogsTable holds the schema information for the "key_rotation_logs" table.
	KeyRotationLogsTable = &schema.Table{
		Name:       "key_rotation_logs",
		Columns:    KeyRotationLogsColumns,
		PrimaryKey: []*schema.Column{KeyRotationLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "key_rotation_logs_signing_keys_rotation_logs",
				Columns:    []*schema.Column{KeyRotationLogsColumns[5]},
				RefColumns: []*schema.Column{SigningKeysColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
	}
	// LoginAttemptsColumns holds the columns for the "login_attempts" table.
	LoginAttemptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "identifier", Type: field.TypeString},
		{Name: "ip_address", Type: field.TypeString, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString},
		{Name: "failure_reason", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LoginAttemptsTable holds the schema information for the "login_attempts" table.
	LoginAttemptsTable = &schema.Table{
		Name:       "login_attempts",
		Columns:    LoginAttemptsColumns,
		PrimaryKey: []*schema.Column{LoginAttemptsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "loginattempt_identifier_created_at",
				Unique:  false,
				Columns: []*schema.Column{LoginAttemptsColumns[1], LoginAttemptsColumns[6]},
			},
			{
				Name:    "loginattempt_ip_address_created_at",
				Unique:  false,
				Columns: []*schema.Column{LoginAttemptsColumns[2], LoginAttemptsColumns[6]},
			},
		},
	}
	// MfaBackupCodesColumns holds the columns for the "mfa_backup_codes" table.
	MfaBackupCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "batch_id", Type: field.TypeString},
		{Name: "code_hash", Type: field.TypeString},
		{Name: "used", Type: field.TypeBool, Default: false},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
	}
	// MfaBackupCodesTable holds the schema information for the "mfa_backup_codes" table.
	MfaBackupCodesTable = &schema.Table{
		Name:       "mfa_backup_codes",
		Columns:    MfaBackupCodesColumns,
		PrimaryKey: []*schema.Column{MfaBackupCodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mfa_backup_codes_users_mfa_backup_codes",
				Columns:    []*schema.Column{MfaBackupCodesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mfabackupcode_user_id_batch_id",
				Unique:  false,
				Columns: []*schema.Column{MfaBackupCodesColumns[7], MfaBackupCodesColumns[1]},
			},
			{
				Name:    "mfabackupcode_code_hash",
				Unique:  false,
				Columns: []*schema.Column{MfaBackupCodesColumns[2]},
			},
		},
	}
	// MfaMethodsColumns holds the columns for the "mfa_methods" table.
	MfaMethodsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "secret_encrypted", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "credential_id", Type: field.TypeString, Nullable: true},
		{Name: "public_key", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_discoverable", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeString},
	}
	// MfaMethodsTable holds the schema information for the "mfa_methods" table.
	MfaMethodsTable = &schema.Table{
		Name:       "mfa_methods",
		Columns:    MfaMethodsColumns,
		PrimaryKey: []*schema.Column{MfaMethodsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "mfa_methods_users_mfa_methods",
				Columns:    []*schema.Column{MfaMethodsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "mfamethod_user_id_type",
				Unique:  false,
				Columns: []*schema.Column{MfaMethodsColumns[10], MfaMethodsColumns[1]},
			},
		},
	}
	// PasswordResetTokensColumns holds the columns for the "password_reset_tokens" table.
	PasswordResetTokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "used", Type: field.TypeBool, Default: false},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
		{Name: "requested_ip", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeString},
	}
	// PasswordResetTokensTable holds the schema information for the "password_reset_tokens" table.
	PasswordResetTokensTable = &schema.Table{
		Name:       "password_reset_tokens",
		Columns:    PasswordResetTokensColumns,
		PrimaryKey: []*schema.Column{PasswordResetTokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "password_reset_tokens_users_password_reset_tokens",
				Columns:    []*schema.Column{PasswordResetTokensColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "resource", Type: field.TypeString},
		{Name: "action", Type: field.TypeString},
		{Name: "scope", Type: field.TypeString},
		{Name: "constraints", Type: field.TypeJSON, Nullable: true},
		{Name: "realm_id", Type: field.TypeString},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "permissions_realms_permissions",
				Columns:    []*schema.Column{PermissionsColumns[10]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "permission_realm_id_name",
				Unique:  true,
				Columns: []*schema.Column{PermissionsColumns[10], PermissionsColumns[1]},
			},
		},
	}
	// RealmsColumns holds the columns for the "realms" table.
	RealmsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "is_system_realm", Type: field.TypeBool, Default: false},
		{Name: "display_name", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "active"},
	}
	// RealmsTable holds the schema information for the "realms" table.
	RealmsTable = &schema.Table{
		Name:       "realms",
		Columns:    RealmsColumns,
		PrimaryKey: []*schema.Column{RealmsColumns[0]},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "managed_by", Type: field.TypeString, Default: "ui"},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "realm_id", Type: field.TypeString},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "roles_realms_roles",
				Columns:    []*schema.Column{RolesColumns[7]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "role_realm_id_name",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[7], RolesColumns[2]},
			},
		},
	}
	// RoleClientScopesColumns holds the columns for the "role_client_scopes" table.
	RoleClientScopesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "granted_at", Type: field.TypeTime},
		{Name: "role_id", Type: field.TypeString},
		{Name: "client_scope_id", Type: field.TypeString},
	}
	// RoleClientScopesTable holds the schema information for the "role_client_scopes" table.
	RoleClientScopesTable = &schema.Table{
		Name:       "role_client_scopes",
		Columns:    RoleClientScopesColumns,
		PrimaryKey: []*schema.Column{RoleClientScopesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_client_scopes_roles_role",
				Columns:    []*schema.Column{RoleClientScopesColumns[2]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_client_scopes_client_scopes_client_scope",
				Columns:    []*schema.Column{RoleClientScopesColumns[3]},
				RefColumns: []*schema.Column{ClientScopesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "roleclientscope_role_id_client_scope_id",
				Unique:  true,
				Columns: []*schema.Column{RoleClientScopesColumns[2], RoleClientScopesColumns[3]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_activity_at", Type: field.TypeTime},
		{Name: "ip_address", Type: field.TypeString, Nullable: true},
		{Name: "user_agent", Type: field.TypeString, Nullable: true},
		{Name: "device_fingerprint", Type: field.TypeString, Nullable: true},
		{Name: "mfa_verified", Type: field.TypeBool, Default: false},
		{Name: "mfa_method_type", Type: field.TypeString, Nullable: true},
		{Name: "auth_method", Type: field.TypeString, Default: "password"},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "revoked_reason", Type: field.TypeString, Nullable: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true},
		{Name: "realm_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeString},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_realms_sessions",
				Columns:    []*schema.Column{SessionsColumns[13]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[14]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "session_user_id_status",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[14], SessionsColumns[10]},
			},
		},
	}
	// SigningKeysColumns holds the columns for the "signing_keys" table.
	SigningKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "key_type", Type: field.TypeString},
		{Name: "purpose", Type: field.TypeString},
		{Name: "kms_key_reference", Type: field.TypeString},
		{Name: "kms_backend", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "kid", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "retired_at", Type: field.TypeTime, Nullable: true},
		{Name: "realm_id", Type: field.TypeString},
	}
	// SigningKeysTable holds the schema information for the "signing_keys" table.
	SigningKeysTable = &schema.Table{
		Name:       "signing_keys",
		Columns:    SigningKeysColumns,
		PrimaryKey: []*schema.Column{SigningKeysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "signing_keys_realms_signing_keys",
				Columns:    []*schema.Column{SigningKeysColumns[11]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
	}
	// TimeoutsColumns holds the columns for the "timeouts" table.
	TimeoutsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "target_type", Type: field.TypeString},
		{Name: "target_id", Type: field.TypeString},
		{Name: "starts_at", Type: field.TypeTime},
		{Name: "ends_at", Type: field.TypeTime, Nullable: true},
		{Name: "reason", Type: field.TypeString},
		{Name: "created_by", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "realm_id", Type: field.TypeString},
	}
	// TimeoutsTable holds the schema information for the "timeouts" table.
	TimeoutsTable = &schema.Table{
		Name:       "timeouts",
		Columns:    TimeoutsColumns,
		PrimaryKey: []*schema.Column{TimeoutsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "timeouts_realms_timeouts",
				Columns:    []*schema.Column{TimeoutsColumns[8]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "timeout_target_type_target_id_ends_at",
				Unique:  false,
				Columns: []*schema.Column{TimeoutsColumns[1], TimeoutsColumns[2], TimeoutsColumns[4]},
			},
		},
	}
	// TokensColumns holds the columns for the "tokens" table.
	TokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "jti", Type: field.TypeString, Unique: true},
		{Name: "issued_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "revoked", Type: field.TypeBool, Default: false},
		{Name: "scopes", Type: field.TypeJSON, Nullable: true},
		{Name: "client_ref_id", Type: field.TypeString},
		{Name: "session_id", Type: field.TypeString},
	}
	// TokensTable holds the schema information for the "tokens" table.
	TokensTable = &schema.Table{
		Name:       "tokens",
		Columns:    TokensColumns,
		PrimaryKey: []*schema.Column{TokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tokens_client_apps_tokens",
				Columns:    []*schema.Column{TokensColumns[7]},
				RefColumns: []*schema.Column{ClientAppsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tokens_sessions_tokens",
				Columns:    []*schema.Column{TokensColumns[8]},
				RefColumns: []*schema.Column{SessionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "token_session_id_revoked",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[8], TokensColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "email", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
		{Name: "profile", Type: field.TypeJSON, Nullable: true},
		{Name: "realm_id", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_realms_users",
				Columns:    []*schema.Column{UsersColumns[10]},
				RefColumns: []*schema.Column{RealmsColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_realm_id_username",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[10], UsersColumns[1]},
			},
			{
				Name:    "user_realm_id_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[10], UsersColumns[3]},
			},
		},
	}
	// GroupPermissionsColumns holds the columns for the "group_permissions" table.
	GroupPermissionsColumns = []*schema.Column{
		{Name: "group_id", Type: field.TypeString},
		{Name: "permission_id", Type: field.TypeString},
	}
	// GroupPermissionsTable holds the schema information for the "group_permissions" table.
	GroupPermissionsTable = &schema.Table{
		Name:       "group_permissions",
		Columns:    GroupPermissionsColumns,
		PrimaryKey: []*schema.Column{GroupPermissionsColumns[0], GroupPermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "group_permissions_group_id",
				Columns:    []*schema.Column{GroupPermissionsColumns[0]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "group_permissions_permission_id",
				Columns:    []*schema.Column{GroupPermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "role_id", Type: field.TypeString},
		{Name: "permission_id", Type: field.TypeString},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0], RolePermissionsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_role_id",
				Columns:    []*schema.Column{RolePermissionsColumns[0]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "role_permissions_permission_id",
				Columns:    []*schema.Column{RolePermissionsColumns[1]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeString},
		{Name: "role_id", Type: field.TypeString},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0], UserRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_user_id",
				Columns:    []*schema.Column{UserRolesColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_roles_role_id",
				Columns:    []*schema.Column{UserRolesColumns[1]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UserGroupsColumns holds the columns for the "user_groups" table.
	UserGroupsColumns = []*schema.Column{
		{Name: "user_id", Type: field.TypeString},
		{Name: "group_id", Type: field.TypeString},
	}
	// UserGroupsTable holds the schema information for the "user_groups" table.
	UserGroupsTable = &schema.Table{
		Name:       "user_groups",
		Columns:    UserGroupsColumns,
		PrimaryKey: []*schema.Column{UserGroupsColumns[0], UserGroupsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_groups_user_id",
				Columns:    []*schema.Column{UserGroupsColumns[0]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "user_groups_group_id",
				Columns:    []*schema.Column{UserGroupsColumns[1]},
				RefColumns: []*schema.Column{GroupsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AuditLogsTable,
		ClientAppsTable,
		ClientGroupsTable,
		ClientRolesTable,
		ClientScopesTable,
		ClientScopeMappingsTable,
		ConsentsTable,
		FederatedIdentitiesTable,
		GroupsTable,
		GroupClientScopesTable,
		IdentityProvidersTable,
		InstanceSettingsTable,
		KeyRotationLogsTable,
		LoginAttemptsTable,
		MfaBackupCodesTable,
		MfaMethodsTable,
		PasswordResetTokensTable,
		PermissionsTable,
		RealmsTable,
		RolesTable,
		RoleClientScopesTable,
		SessionsTable,
		SigningKeysTable,
		TimeoutsTable,
		TokensTable,
		UsersTable,
		GroupPermissionsTable,
		RolePermissionsTable,
		UserRolesTable,
		UserGroupsTable,
	}
)

func init() {
	AuditLogsTable.ForeignKeys[0].RefTable = RealmsTable
	ClientAppsTable.ForeignKeys[0].RefTable = RealmsTable
	ClientGroupsTable.ForeignKeys[0].RefTable = ClientAppsTable
	ClientGroupsTable.ForeignKeys[1].RefTable = GroupsTable
	ClientRolesTable.ForeignKeys[0].RefTable = ClientAppsTable
	ClientRolesTable.ForeignKeys[1].RefTable = RolesTable
	ClientScopesTable.ForeignKeys[0].RefTable = RealmsTable
	ClientScopeMappingsTable.ForeignKeys[0].RefTable = ClientAppsTable
	ClientScopeMappingsTable.ForeignKeys[1].RefTable = ClientScopesTable
	ConsentsTable.ForeignKeys[0].RefTable = ClientAppsTable
	ConsentsTable.ForeignKeys[1].RefTable = UsersTable
	FederatedIdentitiesTable.ForeignKeys[0].RefTable = IdentityProvidersTable
	FederatedIdentitiesTable.ForeignKeys[1].RefTable = UsersTable
	GroupsTable.ForeignKeys[0].RefTable = RealmsTable
	GroupClientScopesTable.ForeignKeys[0].RefTable = GroupsTable
	GroupClientScopesTable.ForeignKeys[1].RefTable = ClientScopesTable
	IdentityProvidersTable.ForeignKeys[0].RefTable = RealmsTable
	InstanceSettingsTable.ForeignKeys[0].RefTable = RealmsTable
	KeyRotationLogsTable.ForeignKeys[0].RefTable = SigningKeysTable
	MfaBackupCodesTable.ForeignKeys[0].RefTable = UsersTable
	MfaMethodsTable.ForeignKeys[0].RefTable = UsersTable
	PasswordResetTokensTable.ForeignKeys[0].RefTable = UsersTable
	PermissionsTable.ForeignKeys[0].RefTable = RealmsTable
	RolesTable.ForeignKeys[0].RefTable = RealmsTable
	RoleClientScopesTable.ForeignKeys[0].RefTable = RolesTable
	RoleClientScopesTable.ForeignKeys[1].RefTable = ClientScopesTable
	SessionsTable.ForeignKeys[0].RefTable = RealmsTable
	SessionsTable.ForeignKeys[1].RefTable = UsersTable
	SigningKeysTable.ForeignKeys[0].RefTable = RealmsTable
	TimeoutsTable.ForeignKeys[0].RefTable = RealmsTable
	TokensTable.ForeignKeys[0].RefTable = ClientAppsTable
	TokensTable.ForeignKeys[1].RefTable = SessionsTable
	UsersTable.ForeignKeys[0].RefTable = RealmsTable
	GroupPermissionsTable.ForeignKeys[0].RefTable = GroupsTable
	GroupPermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
	RolePermissionsTable.ForeignKeys[0].RefTable = RolesTable
	RolePermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
	UserRolesTable.ForeignKeys[0].RefTable = UsersTable
	UserRolesTable.ForeignKeys[1].RefTable = RolesTable
	UserGroupsTable.ForeignKeys[0].RefTable = UsersTable
	UserGroupsTable.ForeignKeys[1].RefTable = GroupsTable
}
