// Code generated by ent, DO NOT EDIT.

package timeout

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the timeout type in the database.
	Label = "timeout"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRealmID holds the string denoting the realm_id field in the database.
	FieldRealmID = "realm_id"
	// FieldTargetType holds the string denoting the target_type field in the database.
	FieldTargetType = "target_type"
	// FieldTargetID holds the string denoting the target_id field in the database.
	FieldTargetID = "target_id"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldEndsAt holds the string denoting the ends_at field in the database.
	FieldEndsAt = "ends_at"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeRealm holds the string denoting the realm edge name in mutations.
	EdgeRealm = "realm"
	// Table holds the table name of the timeout in the database.
	Table = "timeouts"
	// RealmTable is the table that holds the realm relation/edge.
	RealmTable = "timeouts"
	// RealmInverseTable is the table name for the Realm entity.
	// It exists in this package in order to avoid circular dependency with the "realm" package.
	RealmInverseTable = "realms"
	// RealmColumn is the table column denoting the realm relation/edge.
	RealmColumn = "realm_id"
)

// Columns holds all SQL columns for timeout fields.
var Columns = []string{
	FieldID,
	FieldRealmID,
	FieldTargetType,
	FieldTargetID,
	FieldStartsAt,
	FieldEndsAt,
	FieldReason,
	FieldCreatedBy,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RealmIDValidator is a validator for the "realm_id" field. It is called by the builders before save.
	RealmIDValidator func(string) error
	// TargetIDValidator is a validator for the "target_id" field. It is called by the builders before save.
	TargetIDValidator func(string) error
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Timeout queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRealmID orders the results by the realm_id field.
func ByRealmID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealmID, opts...).ToFunc()
}

// ByTargetType orders the results by the target_type field.
func ByTargetType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetType, opts...).ToFunc()
}

// ByTargetID orders the results by the target_id field.
func ByTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetID, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByEndsAt orders the results by the ends_at field.
func ByEndsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndsAt, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByRealmField orders the results by realm field.
func ByRealmField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRealmStep(), sql.OrderByField(field, opts...))
	}
}
func newRealmStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RealmInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RealmTable, RealmColumn),
	)
}
