// Code generated by ent, DO NOT EDIT.

package roleclientscope

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the roleclientscope type in the database.
	Label = "role_client_scope"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// FieldClientScopeID holds the string denoting the client_scope_id field in the database.
	FieldClientScopeID = "client_scope_id"
	// FieldGrantedAt holds the string denoting the granted_at field in the database.
	FieldGrantedAt = "granted_at"
	// EdgeRole holds the string denoting the role edge name in mutations.
	EdgeRole = "role"
	// EdgeClientScope holds the string denoting the client_scope edge name in mutations.
	EdgeClientScope = "client_scope"
	// Table holds the table name of the roleclientscope in the database.
	Table = "role_client_scopes"
	// RoleTable is the table that holds the role relation/edge.
	RoleTable = "role_client_scopes"
	// RoleInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RoleInverseTable = "roles"
	// RoleColumn is the table column denoting the role relation/edge.
	RoleColumn = "role_id"
	// ClientScopeTable is the table that holds the client_scope relation/edge.
	ClientScopeTable = "role_client_scopes"
	// ClientScopeInverseTable is the table name for the ClientScope entity.
	// It exists in this package in order to avoid circular dependency with the "clientscope" package.
	ClientScopeInverseTable = "client_scopes"
	// ClientScopeColumn is the table column denoting the client_scope relation/edge.
	ClientScopeColumn = "client_scope_id"
)

// Columns holds all SQL columns for roleclientscope fields.
var Columns = []string{
	FieldID,
	FieldRoleID,
	FieldClientScopeID,
	FieldGrantedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RoleIDValidator is a validator for the "role_id" field. It is called by the builders before save.
	RoleIDValidator func(string) error
	// ClientScopeIDValidator is a validator for the "client_scope_id" field. It is called by the builders before save.
	ClientScopeIDValidator func(string) error
	// DefaultGrantedAt holds the default value on creation for the "granted_at" field.
	DefaultGrantedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the RoleClientScope queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRoleID orders the results by the role_id field.
func ByRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleID, opts...).ToFunc()
}

// ByClientScopeID orders the results by the client_scope_id field.
func ByClientScopeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientScopeID, opts...).ToFunc()
}

// ByGrantedAt orders the results by the granted_at field.
func ByGrantedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGrantedAt, opts...).ToFunc()
}

// ByRoleField orders the results by role field.
func ByRoleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoleStep(), sql.OrderByField(field, opts...))
	}
}

// ByClientScopeField orders the results by client_scope field.
func ByClientScopeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClientScopeStep(), sql.OrderByField(field, opts...))
	}
}
func newRoleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RoleTable, RoleColumn),
	)
}
func newClientScopeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClientScopeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ClientScopeTable, ClientScopeColumn),
	)
}
