// Code generated by ent, DO NOT EDIT.

package roleclientscope

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"sso.internal/sso/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldContainsFold(FieldID, id))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEQ(FieldRoleID, v))
}

// ClientScopeID applies equality check predicate on the "client_scope_id" field. It's identical to ClientScopeIDEQ.
func ClientScopeID(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEQ(FieldClientScopeID, v))
}

// GrantedAt applies equality check predicate on the "granted_at" field. It's identical to GrantedAtEQ.
func GrantedAt(v time.Time) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEQ(FieldGrantedAt, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDContains applies the Contains predicate on the "role_id" field.
func RoleIDContains(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldContains(FieldRoleID, v))
}

// RoleIDHasPrefix applies the HasPrefix predicate on the "role_id" field.
func RoleIDHasPrefix(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldHasPrefix(FieldRoleID, v))
}

// RoleIDHasSuffix applies the HasSuffix predicate on the "role_id" field.
func RoleIDHasSuffix(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldHasSuffix(FieldRoleID, v))
}

// RoleIDEqualFold applies the EqualFold predicate on the "role_id" field.
func RoleIDEqualFold(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEqualFold(FieldRoleID, v))
}

// RoleIDContainsFold applies the ContainsFold predicate on the "role_id" field.
func RoleIDContainsFold(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldContainsFold(FieldRoleID, v))
}

// ClientScopeIDEQ applies the EQ predicate on the "client_scope_id" field.
func ClientScopeIDEQ(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEQ(FieldClientScopeID, v))
}

// ClientScopeIDNEQ applies the NEQ predicate on the "client_scope_id" field.
func ClientScopeIDNEQ(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldNEQ(FieldClientScopeID, v))
}

// ClientScopeIDIn applies the In predicate on the "client_scope_id" field.
func ClientScopeIDIn(vs ...string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldIn(FieldClientScopeID, vs...))
}

// ClientScopeIDNotIn applies the NotIn predicate on the "client_scope_id" field.
func ClientScopeIDNotIn(vs ...string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldNotIn(FieldClientScopeID, vs...))
}

// ClientScopeIDGT applies the GT predicate on the "client_scope_id" field.
func ClientScopeIDGT(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldGT(FieldClientScopeID, v))
}

// ClientScopeIDGTE applies the GTE predicate on the "client_scope_id" field.
func ClientScopeIDGTE(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldGTE(FieldClientScopeID, v))
}

// ClientScopeIDLT applies the LT predicate on the "client_scope_id" field.
func ClientScopeIDLT(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldLT(FieldClientScopeID, v))
}

// ClientScopeIDLTE applies the LTE predicate on the "client_scope_id" field.
func ClientScopeIDLTE(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldLTE(FieldClientScopeID, v))
}

// ClientScopeIDContains applies the Contains predicate on the "client_scope_id" field.
func ClientScopeIDContains(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldContains(FieldClientScopeID, v))
}

// ClientScopeIDHasPrefix applies the HasPrefix predicate on the "client_scope_id" field.
func ClientScopeIDHasPrefix(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldHasPrefix(FieldClientScopeID, v))
}

// ClientScopeIDHasSuffix applies the HasSuffix predicate on the "client_scope_id" field.
func ClientScopeIDHasSuffix(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldHasSuffix(FieldClientScopeID, v))
}

// ClientScopeIDEqualFold applies the EqualFold predicate on the "client_scope_id" field.
func ClientScopeIDEqualFold(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEqualFold(FieldClientScopeID, v))
}

// ClientScopeIDContainsFold applies the ContainsFold predicate on the "client_scope_id" field.
func ClientScopeIDContainsFold(v string) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldContainsFold(FieldClientScopeID, v))
}

// GrantedAtEQ applies the EQ predicate on the "granted_at" field.
func GrantedAtEQ(v time.Time) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldEQ(FieldGrantedAt, v))
}

// GrantedAtNEQ applies the NEQ predicate on the "granted_at" field.
func GrantedAtNEQ(v time.Time) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldNEQ(FieldGrantedAt, v))
}

// GrantedAtIn applies the In predicate on the "granted_at" field.
func GrantedAtIn(vs ...time.Time) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldIn(FieldGrantedAt, vs...))
}

// GrantedAtNotIn applies the NotIn predicate on the "granted_at" field.
func GrantedAtNotIn(vs ...time.Time) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldNotIn(FieldGrantedAt, vs...))
}

// GrantedAtGT applies the GT predicate on the "granted_at" field.
func GrantedAtGT(v time.Time) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldGT(FieldGrantedAt, v))
}

// GrantedAtGTE applies the GTE predicate on the "granted_at" field.
func GrantedAtGTE(v time.Time) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldGTE(FieldGrantedAt, v))
}

// GrantedAtLT applies the LT predicate on the "granted_at" field.
func GrantedAtLT(v time.Time) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldLT(FieldGrantedAt, v))
}

// GrantedAtLTE applies the LTE predicate on the "granted_at" field.
func GrantedAtLTE(v time.Time) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.FieldLTE(FieldGrantedAt, v))
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.RoleClientScope {
	return predicate.RoleClientScope(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.RoleClientScope {
	return predicate.RoleClientScope(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasClientScope applies the HasEdge predicate on the "client_scope" edge.
func HasClientScope() predicate.RoleClientScope {
	return predicate.RoleClientScope(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ClientScopeTable, ClientScopeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClientScopeWith applies the HasEdge predicate on the "client_scope" edge with a given conditions (other predicates).
func HasClientScopeWith(preds ...predicate.ClientScope) predicate.RoleClientScope {
	return predicate.RoleClientScope(func(s *sql.Selector) {
		step := newClientScopeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoleClientScope) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoleClientScope) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoleClientScope) predicate.RoleClientScope {
	return predicate.RoleClientScope(sql.NotPredicates(p))
}
