// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"sso.internal/sso/ent/clientapp"
	"sso.internal/sso/ent/clientgroup"
	"sso.internal/sso/ent/clientrole"
	"sso.internal/sso/ent/clientscope"
	"sso.internal/sso/ent/clientscopemapping"
	"sso.internal/sso/ent/consent"
	"sso.internal/sso/ent/group"
	"sso.internal/sso/ent/predicate"
	"sso.internal/sso/ent/role"
	"sso.internal/sso/ent/schema"
	"sso.internal/sso/ent/token"
)

// ClientAppUpdate is the builder for updating ClientApp entities.
type ClientAppUpdate struct {
	config
	hooks    []Hook
	mutation *ClientAppMutation
}

// Where appends a list predicates to the ClientAppUpdate builder.
func (_u *ClientAppUpdate) Where(ps ...predicate.ClientApp) *ClientAppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetManagedBy sets the "managed_by" field.
func (_u *ClientAppUpdate) SetManagedBy(v schema.ClientAppManagedBy) *ClientAppUpdate {
	_u.mutation.SetManagedBy(v)
	return _u
}

// SetNillableManagedBy sets the "managed_by" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableManagedBy(v *schema.ClientAppManagedBy) *ClientAppUpdate {
	if v != nil {
		_u.SetManagedBy(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ClientAppUpdate) SetName(v string) *ClientAppUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableName(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ClientAppUpdate) SetStatus(v schema.ClientAppStatus) *ClientAppUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableStatus(v *schema.ClientAppStatus) *ClientAppUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClientAppUpdate) SetUpdatedAt(v time.Time) *ClientAppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ClientAppUpdate) SetDeletedAt(v time.Time) *ClientAppUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableDeletedAt(v *time.Time) *ClientAppUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ClientAppUpdate) ClearDeletedAt() *ClientAppUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerAdminID sets the "owner_admin_id" field.
func (_u *ClientAppUpdate) SetOwnerAdminID(v string) *ClientAppUpdate {
	_u.mutation.SetOwnerAdminID(v)
	return _u
}

// SetNillableOwnerAdminID sets the "owner_admin_id" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableOwnerAdminID(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetOwnerAdminID(*v)
	}
	return _u
}

// ClearOwnerAdminID clears the value of the "owner_admin_id" field.
func (_u *ClientAppUpdate) ClearOwnerAdminID() *ClientAppUpdate {
	_u.mutation.ClearOwnerAdminID()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ClientAppUpdate) SetClientID(v string) *ClientAppUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableClientID(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *ClientAppUpdate) ClearClientID() *ClientAppUpdate {
	_u.mutation.ClearClientID()
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *ClientAppUpdate) SetClientSecretHash(v string) *ClientAppUpdate {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableClientSecretHash(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// ClearClientSecretHash clears the value of the "client_secret_hash" field.
func (_u *ClientAppUpdate) ClearClientSecretHash() *ClientAppUpdate {
	_u.mutation.ClearClientSecretHash()
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *ClientAppUpdate) SetClientType(v schema.ClientAppType) *ClientAppUpdate {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableClientType(v *schema.ClientAppType) *ClientAppUpdate {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// ClearClientType clears the value of the "client_type" field.
func (_u *ClientAppUpdate) ClearClientType() *ClientAppUpdate {
	_u.mutation.ClearClientType()
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *ClientAppUpdate) SetRedirectUris(v []string) *ClientAppUpdate {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *ClientAppUpdate) AppendRedirectUris(v []string) *ClientAppUpdate {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// ClearRedirectUris clears the value of the "redirect_uris" field.
func (_u *ClientAppUpdate) ClearRedirectUris() *ClientAppUpdate {
	_u.mutation.ClearRedirectUris()
	return _u
}

// SetPostLogoutRedirectUris sets the "post_logout_redirect_uris" field.
func (_u *ClientAppUpdate) SetPostLogoutRedirectUris(v []string) *ClientAppUpdate {
	_u.mutation.SetPostLogoutRedirectUris(v)
	return _u
}

// AppendPostLogoutRedirectUris appends value to the "post_logout_redirect_uris" field.
func (_u *ClientAppUpdate) AppendPostLogoutRedirectUris(v []string) *ClientAppUpdate {
	_u.mutation.AppendPostLogoutRedirectUris(v)
	return _u
}

// ClearPostLogoutRedirectUris clears the value of the "post_logout_redirect_uris" field.
func (_u *ClientAppUpdate) ClearPostLogoutRedirectUris() *ClientAppUpdate {
	_u.mutation.ClearPostLogoutRedirectUris()
	return _u
}

// SetAllowedGrantTypes sets the "allowed_grant_types" field.
func (_u *ClientAppUpdate) SetAllowedGrantTypes(v []string) *ClientAppUpdate {
	_u.mutation.SetAllowedGrantTypes(v)
	return _u
}

// AppendAllowedGrantTypes appends value to the "allowed_grant_types" field.
func (_u *ClientAppUpdate) AppendAllowedGrantTypes(v []string) *ClientAppUpdate {
	_u.mutation.AppendAllowedGrantTypes(v)
	return _u
}

// ClearAllowedGrantTypes clears the value of the "allowed_grant_types" field.
func (_u *ClientAppUpdate) ClearAllowedGrantTypes() *ClientAppUpdate {
	_u.mutation.ClearAllowedGrantTypes()
	return _u
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (_u *ClientAppUpdate) SetAllowedScopes(v []string) *ClientAppUpdate {
	_u.mutation.SetAllowedScopes(v)
	return _u
}

// AppendAllowedScopes appends value to the "allowed_scopes" field.
func (_u *ClientAppUpdate) AppendAllowedScopes(v []string) *ClientAppUpdate {
	_u.mutation.AppendAllowedScopes(v)
	return _u
}

// ClearAllowedScopes clears the value of the "allowed_scopes" field.
func (_u *ClientAppUpdate) ClearAllowedScopes() *ClientAppUpdate {
	_u.mutation.ClearAllowedScopes()
	return _u
}

// SetTokenEndpointAuthMethod sets the "token_endpoint_auth_method" field.
func (_u *ClientAppUpdate) SetTokenEndpointAuthMethod(v string) *ClientAppUpdate {
	_u.mutation.SetTokenEndpointAuthMethod(v)
	return _u
}

// SetNillableTokenEndpointAuthMethod sets the "token_endpoint_auth_method" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableTokenEndpointAuthMethod(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetTokenEndpointAuthMethod(*v)
	}
	return _u
}

// ClearTokenEndpointAuthMethod clears the value of the "token_endpoint_auth_method" field.
func (_u *ClientAppUpdate) ClearTokenEndpointAuthMethod() *ClientAppUpdate {
	_u.mutation.ClearTokenEndpointAuthMethod()
	return _u
}

// SetIDTokenSignedAlg sets the "id_token_signed_alg" field.
func (_u *ClientAppUpdate) SetIDTokenSignedAlg(v string) *ClientAppUpdate {
	_u.mutation.SetIDTokenSignedAlg(v)
	return _u
}

// SetNillableIDTokenSignedAlg sets the "id_token_signed_alg" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableIDTokenSignedAlg(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetIDTokenSignedAlg(*v)
	}
	return _u
}

// ClearIDTokenSignedAlg clears the value of the "id_token_signed_alg" field.
func (_u *ClientAppUpdate) ClearIDTokenSignedAlg() *ClientAppUpdate {
	_u.mutation.ClearIDTokenSignedAlg()
	return _u
}

// SetAccessTokenTTL sets the "access_token_ttl" field.
func (_u *ClientAppUpdate) SetAccessTokenTTL(v int) *ClientAppUpdate {
	_u.mutation.ResetAccessTokenTTL()
	_u.mutation.SetAccessTokenTTL(v)
	return _u
}

// SetNillableAccessTokenTTL sets the "access_token_ttl" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableAccessTokenTTL(v *int) *ClientAppUpdate {
	if v != nil {
		_u.SetAccessTokenTTL(*v)
	}
	return _u
}

// AddAccessTokenTTL adds value to the "access_token_ttl" field.
func (_u *ClientAppUpdate) AddAccessTokenTTL(v int) *ClientAppUpdate {
	_u.mutation.AddAccessTokenTTL(v)
	return _u
}

// SetRefreshTokenTTL sets the "refresh_token_ttl" field.
func (_u *ClientAppUpdate) SetRefreshTokenTTL(v int) *ClientAppUpdate {
	_u.mutation.ResetRefreshTokenTTL()
	_u.mutation.SetRefreshTokenTTL(v)
	return _u
}

// SetNillableRefreshTokenTTL sets the "refresh_token_ttl" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableRefreshTokenTTL(v *int) *ClientAppUpdate {
	if v != nil {
		_u.SetRefreshTokenTTL(*v)
	}
	return _u
}

// AddRefreshTokenTTL adds value to the "refresh_token_ttl" field.
func (_u *ClientAppUpdate) AddRefreshTokenTTL(v int) *ClientAppUpdate {
	_u.mutation.AddRefreshTokenTTL(v)
	return _u
}

// SetIDTokenTTL sets the "id_token_ttl" field.
func (_u *ClientAppUpdate) SetIDTokenTTL(v int) *ClientAppUpdate {
	_u.mutation.ResetIDTokenTTL()
	_u.mutation.SetIDTokenTTL(v)
	return _u
}

// SetNillableIDTokenTTL sets the "id_token_ttl" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableIDTokenTTL(v *int) *ClientAppUpdate {
	if v != nil {
		_u.SetIDTokenTTL(*v)
	}
	return _u
}

// AddIDTokenTTL adds value to the "id_token_ttl" field.
func (_u *ClientAppUpdate) AddIDTokenTTL(v int) *ClientAppUpdate {
	_u.mutation.AddIDTokenTTL(v)
	return _u
}

// SetRequirePkce sets the "require_pkce" field.
func (_u *ClientAppUpdate) SetRequirePkce(v bool) *ClientAppUpdate {
	_u.mutation.SetRequirePkce(v)
	return _u
}

// SetNillableRequirePkce sets the "require_pkce" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableRequirePkce(v *bool) *ClientAppUpdate {
	if v != nil {
		_u.SetRequirePkce(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *ClientAppUpdate) SetEntityID(v string) *ClientAppUpdate {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableEntityID(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *ClientAppUpdate) ClearEntityID() *ClientAppUpdate {
	_u.mutation.ClearEntityID()
	return _u
}

// SetAcsURL sets the "acs_url" field.
func (_u *ClientAppUpdate) SetAcsURL(v string) *ClientAppUpdate {
	_u.mutation.SetAcsURL(v)
	return _u
}

// SetNillableAcsURL sets the "acs_url" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableAcsURL(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetAcsURL(*v)
	}
	return _u
}

// ClearAcsURL clears the value of the "acs_url" field.
func (_u *ClientAppUpdate) ClearAcsURL() *ClientAppUpdate {
	_u.mutation.ClearAcsURL()
	return _u
}

// SetSloURL sets the "slo_url" field.
func (_u *ClientAppUpdate) SetSloURL(v string) *ClientAppUpdate {
	_u.mutation.SetSloURL(v)
	return _u
}

// SetNillableSloURL sets the "slo_url" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableSloURL(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetSloURL(*v)
	}
	return _u
}

// ClearSloURL clears the value of the "slo_url" field.
func (_u *ClientAppUpdate) ClearSloURL() *ClientAppUpdate {
	_u.mutation.ClearSloURL()
	return _u
}

// SetClientCertificates sets the "client_certificates" field.
func (_u *ClientAppUpdate) SetClientCertificates(v []map[string]interface{}) *ClientAppUpdate {
	_u.mutation.SetClientCertificates(v)
	return _u
}

// AppendClientCertificates appends value to the "client_certificates" field.
func (_u *ClientAppUpdate) AppendClientCertificates(v []map[string]interface{}) *ClientAppUpdate {
	_u.mutation.AppendClientCertificates(v)
	return _u
}

// ClearClientCertificates clears the value of the "client_certificates" field.
func (_u *ClientAppUpdate) ClearClientCertificates() *ClientAppUpdate {
	_u.mutation.ClearClientCertificates()
	return _u
}

// SetNameIDFormat sets the "name_id_format" field.
func (_u *ClientAppUpdate) SetNameIDFormat(v string) *ClientAppUpdate {
	_u.mutation.SetNameIDFormat(v)
	return _u
}

// SetNillableNameIDFormat sets the "name_id_format" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableNameIDFormat(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetNameIDFormat(*v)
	}
	return _u
}

// ClearNameIDFormat clears the value of the "name_id_format" field.
func (_u *ClientAppUpdate) ClearNameIDFormat() *ClientAppUpdate {
	_u.mutation.ClearNameIDFormat()
	return _u
}

// SetWantAssertionSigned sets the "want_assertion_signed" field.
func (_u *ClientAppUpdate) SetWantAssertionSigned(v bool) *ClientAppUpdate {
	_u.mutation.SetWantAssertionSigned(v)
	return _u
}

// SetNillableWantAssertionSigned sets the "want_assertion_signed" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableWantAssertionSigned(v *bool) *ClientAppUpdate {
	if v != nil {
		_u.SetWantAssertionSigned(*v)
	}
	return _u
}

// SetWantResponseSigned sets the "want_response_signed" field.
func (_u *ClientAppUpdate) SetWantResponseSigned(v bool) *ClientAppUpdate {
	_u.mutation.SetWantResponseSigned(v)
	return _u
}

// SetNillableWantResponseSigned sets the "want_response_signed" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableWantResponseSigned(v *bool) *ClientAppUpdate {
	if v != nil {
		_u.SetWantResponseSigned(*v)
	}
	return _u
}

// SetDefaultRelayState sets the "default_relay_state" field.
func (_u *ClientAppUpdate) SetDefaultRelayState(v string) *ClientAppUpdate {
	_u.mutation.SetDefaultRelayState(v)
	return _u
}

// SetNillableDefaultRelayState sets the "default_relay_state" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableDefaultRelayState(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetDefaultRelayState(*v)
	}
	return _u
}

// ClearDefaultRelayState clears the value of the "default_relay_state" field.
func (_u *ClientAppUpdate) ClearDefaultRelayState() *ClientAppUpdate {
	_u.mutation.ClearDefaultRelayState()
	return _u
}

// SetAttributeMappings sets the "attribute_mappings" field.
func (_u *ClientAppUpdate) SetAttributeMappings(v map[string]interface{}) *ClientAppUpdate {
	_u.mutation.SetAttributeMappings(v)
	return _u
}

// ClearAttributeMappings clears the value of the "attribute_mappings" field.
func (_u *ClientAppUpdate) ClearAttributeMappings() *ClientAppUpdate {
	_u.mutation.ClearAttributeMappings()
	return _u
}

// SetRequireConsent sets the "require_consent" field.
func (_u *ClientAppUpdate) SetRequireConsent(v bool) *ClientAppUpdate {
	_u.mutation.SetRequireConsent(v)
	return _u
}

// SetNillableRequireConsent sets the "require_consent" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableRequireConsent(v *bool) *ClientAppUpdate {
	if v != nil {
		_u.SetRequireConsent(*v)
	}
	return _u
}

// SetMetadataURL sets the "metadata_url" field.
func (_u *ClientAppUpdate) SetMetadataURL(v string) *ClientAppUpdate {
	_u.mutation.SetMetadataURL(v)
	return _u
}

// SetNillableMetadataURL sets the "metadata_url" field if the given value is not nil.
func (_u *ClientAppUpdate) SetNillableMetadataURL(v *string) *ClientAppUpdate {
	if v != nil {
		_u.SetMetadataURL(*v)
	}
	return _u
}

// ClearMetadataURL clears the value of the "metadata_url" field.
func (_u *ClientAppUpdate) ClearMetadataURL() *ClientAppUpdate {
	_u.mutation.ClearMetadataURL()
	return _u
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *ClientAppUpdate) AddRoleIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *ClientAppUpdate) AddRoles(v ...*Role) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *ClientAppUpdate) AddGroupIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *ClientAppUpdate) AddGroups(v ...*Group) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddClientScopeIDs adds the "client_scopes" edge to the ClientScope entity by IDs.
func (_u *ClientAppUpdate) AddClientScopeIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.AddClientScopeIDs(ids...)
	return _u
}

// AddClientScopes adds the "client_scopes" edges to the ClientScope entity.
func (_u *ClientAppUpdate) AddClientScopes(v ...*ClientScope) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientScopeIDs(ids...)
}

// AddTokenIDs adds the "tokens" edge to the Token entity by IDs.
func (_u *ClientAppUpdate) AddTokenIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.AddTokenIDs(ids...)
	return _u
}

// AddTokens adds the "tokens" edges to the Token entity.
func (_u *ClientAppUpdate) AddTokens(v ...*Token) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenIDs(ids...)
}

// AddConsentIDs adds the "consents" edge to the Consent entity by IDs.
func (_u *ClientAppUpdate) AddConsentIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.AddConsentIDs(ids...)
	return _u
}

// AddConsents adds the "consents" edges to the Consent entity.
func (_u *ClientAppUpdate) AddConsents(v ...*Consent) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConsentIDs(ids...)
}

// AddClientRoleIDs adds the "client_roles" edge to the ClientRole entity by IDs.
func (_u *ClientAppUpdate) AddClientRoleIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.AddClientRoleIDs(ids...)
	return _u
}

// AddClientRoles adds the "client_roles" edges to the ClientRole entity.
func (_u *ClientAppUpdate) AddClientRoles(v ...*ClientRole) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientRoleIDs(ids...)
}

// AddClientGroupIDs adds the "client_groups" edge to the ClientGroup entity by IDs.
func (_u *ClientAppUpdate) AddClientGroupIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.AddClientGroupIDs(ids...)
	return _u
}

// AddClientGroups adds the "client_groups" edges to the ClientGroup entity.
func (_u *ClientAppUpdate) AddClientGroups(v ...*ClientGroup) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientGroupIDs(ids...)
}

// AddClientScopeMappingIDs adds the "client_scope_mappings" edge to the ClientScopeMapping entity by IDs.
func (_u *ClientAppUpdate) AddClientScopeMappingIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.AddClientScopeMappingIDs(ids...)
	return _u
}

// AddClientScopeMappings adds the "client_scope_mappings" edges to the ClientScopeMapping entity.
func (_u *ClientAppUpdate) AddClientScopeMappings(v ...*ClientScopeMapping) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientScopeMappingIDs(ids...)
}

// Mutation returns the ClientAppMutation object of the builder.
func (_u *ClientAppUpdate) Mutation() *ClientAppMutation {
	return _u.mutation
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *ClientAppUpdate) ClearRoles() *ClientAppUpdate {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *ClientAppUpdate) RemoveRoleIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *ClientAppUpdate) RemoveRoles(v ...*Role) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *ClientAppUpdate) ClearGroups() *ClientAppUpdate {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *ClientAppUpdate) RemoveGroupIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *ClientAppUpdate) RemoveGroups(v ...*Group) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearClientScopes clears all "client_scopes" edges to the ClientScope entity.
func (_u *ClientAppUpdate) ClearClientScopes() *ClientAppUpdate {
	_u.mutation.ClearClientScopes()
	return _u
}

// RemoveClientScopeIDs removes the "client_scopes" edge to ClientScope entities by IDs.
func (_u *ClientAppUpdate) RemoveClientScopeIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.RemoveClientScopeIDs(ids...)
	return _u
}

// RemoveClientScopes removes "client_scopes" edges to ClientScope entities.
func (_u *ClientAppUpdate) RemoveClientScopes(v ...*ClientScope) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientScopeIDs(ids...)
}

// ClearTokens clears all "tokens" edges to the Token entity.
func (_u *ClientAppUpdate) ClearTokens() *ClientAppUpdate {
	_u.mutation.ClearTokens()
	return _u
}

// RemoveTokenIDs removes the "tokens" edge to Token entities by IDs.
func (_u *ClientAppUpdate) RemoveTokenIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.RemoveTokenIDs(ids...)
	return _u
}

// RemoveTokens removes "tokens" edges to Token entities.
func (_u *ClientAppUpdate) RemoveTokens(v ...*Token) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenIDs(ids...)
}

// ClearConsents clears all "consents" edges to the Consent entity.
func (_u *ClientAppUpdate) ClearConsents() *ClientAppUpdate {
	_u.mutation.ClearConsents()
	return _u
}

// RemoveConsentIDs removes the "consents" edge to Consent entities by IDs.
func (_u *ClientAppUpdate) RemoveConsentIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.RemoveConsentIDs(ids...)
	return _u
}

// RemoveConsents removes "consents" edges to Consent entities.
func (_u *ClientAppUpdate) RemoveConsents(v ...*Consent) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConsentIDs(ids...)
}

// ClearClientRoles clears all "client_roles" edges to the ClientRole entity.
func (_u *ClientAppUpdate) ClearClientRoles() *ClientAppUpdate {
	_u.mutation.ClearClientRoles()
	return _u
}

// RemoveClientRoleIDs removes the "client_roles" edge to ClientRole entities by IDs.
func (_u *ClientAppUpdate) RemoveClientRoleIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.RemoveClientRoleIDs(ids...)
	return _u
}

// RemoveClientRoles removes "client_roles" edges to ClientRole entities.
func (_u *ClientAppUpdate) RemoveClientRoles(v ...*ClientRole) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientRoleIDs(ids...)
}

// ClearClientGroups clears all "client_groups" edges to the ClientGroup entity.
func (_u *ClientAppUpdate) ClearClientGroups() *ClientAppUpdate {
	_u.mutation.ClearClientGroups()
	return _u
}

// RemoveClientGroupIDs removes the "client_groups" edge to ClientGroup entities by IDs.
func (_u *ClientAppUpdate) RemoveClientGroupIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.RemoveClientGroupIDs(ids...)
	return _u
}

// RemoveClientGroups removes "client_groups" edges to ClientGroup entities.
func (_u *ClientAppUpdate) RemoveClientGroups(v ...*ClientGroup) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientGroupIDs(ids...)
}

// ClearClientScopeMappings clears all "client_scope_mappings" edges to the ClientScopeMapping entity.
func (_u *ClientAppUpdate) ClearClientScopeMappings() *ClientAppUpdate {
	_u.mutation.ClearClientScopeMappings()
	return _u
}

// RemoveClientScopeMappingIDs removes the "client_scope_mappings" edge to ClientScopeMapping entities by IDs.
func (_u *ClientAppUpdate) RemoveClientScopeMappingIDs(ids ...string) *ClientAppUpdate {
	_u.mutation.RemoveClientScopeMappingIDs(ids...)
	return _u
}

// RemoveClientScopeMappings removes "client_scope_mappings" edges to ClientScopeMapping entities.
func (_u *ClientAppUpdate) RemoveClientScopeMappings(v ...*ClientScopeMapping) *ClientAppUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientScopeMappingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClientAppUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientAppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClientAppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientAppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClientAppUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := clientapp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientAppUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := clientapp.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientApp.name": %w`, err)}
		}
	}
	if _u.mutation.RealmCleared() && len(_u.mutation.RealmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClientApp.realm"`)
	}
	return nil
}

func (_u *ClientAppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientapp.Table, clientapp.Columns, sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ManagedBy(); ok {
		_spec.SetField(clientapp.FieldManagedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(clientapp.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(clientapp.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(clientapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(clientapp.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(clientapp.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerAdminID(); ok {
		_spec.SetField(clientapp.FieldOwnerAdminID, field.TypeString, value)
	}
	if _u.mutation.OwnerAdminIDCleared() {
		_spec.ClearField(clientapp.FieldOwnerAdminID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(clientapp.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(clientapp.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(clientapp.FieldClientSecretHash, field.TypeString, value)
	}
	if _u.mutation.ClientSecretHashCleared() {
		_spec.ClearField(clientapp.FieldClientSecretHash, field.TypeString)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(clientapp.FieldClientType, field.TypeString, value)
	}
	if _u.mutation.ClientTypeCleared() {
		_spec.ClearField(clientapp.FieldClientType, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(clientapp.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldRedirectUris, value)
		})
	}
	if _u.mutation.RedirectUrisCleared() {
		_spec.ClearField(clientapp.FieldRedirectUris, field.TypeJSON)
	}
	if value, ok := _u.mutation.PostLogoutRedirectUris(); ok {
		_spec.SetField(clientapp.FieldPostLogoutRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPostLogoutRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldPostLogoutRedirectUris, value)
		})
	}
	if _u.mutation.PostLogoutRedirectUrisCleared() {
		_spec.ClearField(clientapp.FieldPostLogoutRedirectUris, field.TypeJSON)
	}
	if value, ok := _u.mutation.AllowedGrantTypes(); ok {
		_spec.SetField(clientapp.FieldAllowedGrantTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedGrantTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldAllowedGrantTypes, value)
		})
	}
	if _u.mutation.AllowedGrantTypesCleared() {
		_spec.ClearField(clientapp.FieldAllowedGrantTypes, field.TypeJSON)
	}
	if value, ok := _u.mutation.AllowedScopes(); ok {
		_spec.SetField(clientapp.FieldAllowedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldAllowedScopes, value)
		})
	}
	if _u.mutation.AllowedScopesCleared() {
		_spec.ClearField(clientapp.FieldAllowedScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.TokenEndpointAuthMethod(); ok {
		_spec.SetField(clientapp.FieldTokenEndpointAuthMethod, field.TypeString, value)
	}
	if _u.mutation.TokenEndpointAuthMethodCleared() {
		_spec.ClearField(clientapp.FieldTokenEndpointAuthMethod, field.TypeString)
	}
	if value, ok := _u.mutation.IDTokenSignedAlg(); ok {
		_spec.SetField(clientapp.FieldIDTokenSignedAlg, field.TypeString, value)
	}
	if _u.mutation.IDTokenSignedAlgCleared() {
		_spec.ClearField(clientapp.FieldIDTokenSignedAlg, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenTTL(); ok {
		_spec.SetField(clientapp.FieldAccessTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessTokenTTL(); ok {
		_spec.AddField(clientapp.FieldAccessTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefreshTokenTTL(); ok {
		_spec.SetField(clientapp.FieldRefreshTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshTokenTTL(); ok {
		_spec.AddField(clientapp.FieldRefreshTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IDTokenTTL(); ok {
		_spec.SetField(clientapp.FieldIDTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIDTokenTTL(); ok {
		_spec.AddField(clientapp.FieldIDTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequirePkce(); ok {
		_spec.SetField(clientapp.FieldRequirePkce, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(clientapp.FieldEntityID, field.TypeString, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(clientapp.FieldEntityID, field.TypeString)
	}
	if value, ok := _u.mutation.AcsURL(); ok {
		_spec.SetField(clientapp.FieldAcsURL, field.TypeString, value)
	}
	if _u.mutation.AcsURLCleared() {
		_spec.ClearField(clientapp.FieldAcsURL, field.TypeString)
	}
	if value, ok := _u.mutation.SloURL(); ok {
		_spec.SetField(clientapp.FieldSloURL, field.TypeString, value)
	}
	if _u.mutation.SloURLCleared() {
		_spec.ClearField(clientapp.FieldSloURL, field.TypeString)
	}
	if value, ok := _u.mutation.ClientCertificates(); ok {
		_spec.SetField(clientapp.FieldClientCertificates, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedClientCertificates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldClientCertificates, value)
		})
	}
	if _u.mutation.ClientCertificatesCleared() {
		_spec.ClearField(clientapp.FieldClientCertificates, field.TypeJSON)
	}
	if value, ok := _u.mutation.NameIDFormat(); ok {
		_spec.SetField(clientapp.FieldNameIDFormat, field.TypeString, value)
	}
	if _u.mutation.NameIDFormatCleared() {
		_spec.ClearField(clientapp.FieldNameIDFormat, field.TypeString)
	}
	if value, ok := _u.mutation.WantAssertionSigned(); ok {
		_spec.SetField(clientapp.FieldWantAssertionSigned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WantResponseSigned(); ok {
		_spec.SetField(clientapp.FieldWantResponseSigned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultRelayState(); ok {
		_spec.SetField(clientapp.FieldDefaultRelayState, field.TypeString, value)
	}
	if _u.mutation.DefaultRelayStateCleared() {
		_spec.ClearField(clientapp.FieldDefaultRelayState, field.TypeString)
	}
	if value, ok := _u.mutation.AttributeMappings(); ok {
		_spec.SetField(clientapp.FieldAttributeMappings, field.TypeJSON, value)
	}
	if _u.mutation.AttributeMappingsCleared() {
		_spec.ClearField(clientapp.FieldAttributeMappings, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequireConsent(); ok {
		_spec.SetField(clientapp.FieldRequireConsent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetadataURL(); ok {
		_spec.SetField(clientapp.FieldMetadataURL, field.TypeString, value)
	}
	if _u.mutation.MetadataURLCleared() {
		_spec.ClearField(clientapp.FieldMetadataURL, field.TypeString)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.RolesTable,
			Columns: clientapp.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		createE := &ClientRoleCreate{config: _u.config, mutation: newClientRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.RolesTable,
			Columns: clientapp.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientRoleCreate{config: _u.config, mutation: newClientRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.RolesTable,
			Columns: clientapp.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientRoleCreate{config: _u.config, mutation: newClientRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.GroupsTable,
			Columns: clientapp.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		createE := &ClientGroupCreate{config: _u.config, mutation: newClientGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.GroupsTable,
			Columns: clientapp.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientGroupCreate{config: _u.config, mutation: newClientGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.GroupsTable,
			Columns: clientapp.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientGroupCreate{config: _u.config, mutation: newClientGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientapp.ClientScopesTable,
			Columns: clientapp.ClientScopesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscope.FieldID, field.TypeString),
			},
		}
		createE := &ClientScopeMappingCreate{config: _u.config, mutation: newClientScopeMappingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientScopesIDs(); len(nodes) > 0 && !_u.mutation.ClientScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientapp.ClientScopesTable,
			Columns: clientapp.ClientScopesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscope.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientScopeMappingCreate{config: _u.config, mutation: newClientScopeMappingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientScopesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientapp.ClientScopesTable,
			Columns: clientapp.ClientScopesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscope.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientScopeMappingCreate{config: _u.config, mutation: newClientScopeMappingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.TokensTable,
			Columns: []string{clientapp.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(token.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokensIDs(); len(nodes) > 0 && !_u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.TokensTable,
			Columns: []string{clientapp.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(token.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.TokensTable,
			Columns: []string{clientapp.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(token.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.ConsentsTable,
			Columns: []string{clientapp.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConsentsIDs(); len(nodes) > 0 && !_u.mutation.ConsentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.ConsentsTable,
			Columns: []string{clientapp.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.ConsentsTable,
			Columns: []string{clientapp.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientRolesTable,
			Columns: []string{clientapp.ClientRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientrole.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientRolesIDs(); len(nodes) > 0 && !_u.mutation.ClientRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientRolesTable,
			Columns: []string{clientapp.ClientRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientrole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientRolesTable,
			Columns: []string{clientapp.ClientRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientrole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientGroupsTable,
			Columns: []string{clientapp.ClientGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientgroup.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientGroupsIDs(); len(nodes) > 0 && !_u.mutation.ClientGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientGroupsTable,
			Columns: []string{clientapp.ClientGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientgroup.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientGroupsTable,
			Columns: []string{clientapp.ClientGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientgroup.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientScopeMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientScopeMappingsTable,
			Columns: []string{clientapp.ClientScopeMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscopemapping.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientScopeMappingsIDs(); len(nodes) > 0 && !_u.mutation.ClientScopeMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientScopeMappingsTable,
			Columns: []string{clientapp.ClientScopeMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscopemapping.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientScopeMappingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientScopeMappingsTable,
			Columns: []string{clientapp.ClientScopeMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscopemapping.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClientAppUpdateOne is the builder for updating a single ClientApp entity.
type ClientAppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClientAppMutation
}

// SetManagedBy sets the "managed_by" field.
func (_u *ClientAppUpdateOne) SetManagedBy(v schema.ClientAppManagedBy) *ClientAppUpdateOne {
	_u.mutation.SetManagedBy(v)
	return _u
}

// SetNillableManagedBy sets the "managed_by" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableManagedBy(v *schema.ClientAppManagedBy) *ClientAppUpdateOne {
	if v != nil {
		_u.SetManagedBy(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ClientAppUpdateOne) SetName(v string) *ClientAppUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableName(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ClientAppUpdateOne) SetStatus(v schema.ClientAppStatus) *ClientAppUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableStatus(v *schema.ClientAppStatus) *ClientAppUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClientAppUpdateOne) SetUpdatedAt(v time.Time) *ClientAppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ClientAppUpdateOne) SetDeletedAt(v time.Time) *ClientAppUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableDeletedAt(v *time.Time) *ClientAppUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ClientAppUpdateOne) ClearDeletedAt() *ClientAppUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerAdminID sets the "owner_admin_id" field.
func (_u *ClientAppUpdateOne) SetOwnerAdminID(v string) *ClientAppUpdateOne {
	_u.mutation.SetOwnerAdminID(v)
	return _u
}

// SetNillableOwnerAdminID sets the "owner_admin_id" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableOwnerAdminID(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetOwnerAdminID(*v)
	}
	return _u
}

// ClearOwnerAdminID clears the value of the "owner_admin_id" field.
func (_u *ClientAppUpdateOne) ClearOwnerAdminID() *ClientAppUpdateOne {
	_u.mutation.ClearOwnerAdminID()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ClientAppUpdateOne) SetClientID(v string) *ClientAppUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableClientID(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *ClientAppUpdateOne) ClearClientID() *ClientAppUpdateOne {
	_u.mutation.ClearClientID()
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *ClientAppUpdateOne) SetClientSecretHash(v string) *ClientAppUpdateOne {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableClientSecretHash(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// ClearClientSecretHash clears the value of the "client_secret_hash" field.
func (_u *ClientAppUpdateOne) ClearClientSecretHash() *ClientAppUpdateOne {
	_u.mutation.ClearClientSecretHash()
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *ClientAppUpdateOne) SetClientType(v schema.ClientAppType) *ClientAppUpdateOne {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableClientType(v *schema.ClientAppType) *ClientAppUpdateOne {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// ClearClientType clears the value of the "client_type" field.
func (_u *ClientAppUpdateOne) ClearClientType() *ClientAppUpdateOne {
	_u.mutation.ClearClientType()
	return _u
}

// SetRedirectUris sets the "redirect_uris" field.
func (_u *ClientAppUpdateOne) SetRedirectUris(v []string) *ClientAppUpdateOne {
	_u.mutation.SetRedirectUris(v)
	return _u
}

// AppendRedirectUris appends value to the "redirect_uris" field.
func (_u *ClientAppUpdateOne) AppendRedirectUris(v []string) *ClientAppUpdateOne {
	_u.mutation.AppendRedirectUris(v)
	return _u
}

// ClearRedirectUris clears the value of the "redirect_uris" field.
func (_u *ClientAppUpdateOne) ClearRedirectUris() *ClientAppUpdateOne {
	_u.mutation.ClearRedirectUris()
	return _u
}

// SetPostLogoutRedirectUris sets the "post_logout_redirect_uris" field.
func (_u *ClientAppUpdateOne) SetPostLogoutRedirectUris(v []string) *ClientAppUpdateOne {
	_u.mutation.SetPostLogoutRedirectUris(v)
	return _u
}

// AppendPostLogoutRedirectUris appends value to the "post_logout_redirect_uris" field.
func (_u *ClientAppUpdateOne) AppendPostLogoutRedirectUris(v []string) *ClientAppUpdateOne {
	_u.mutation.AppendPostLogoutRedirectUris(v)
	return _u
}

// ClearPostLogoutRedirectUris clears the value of the "post_logout_redirect_uris" field.
func (_u *ClientAppUpdateOne) ClearPostLogoutRedirectUris() *ClientAppUpdateOne {
	_u.mutation.ClearPostLogoutRedirectUris()
	return _u
}

// SetAllowedGrantTypes sets the "allowed_grant_types" field.
func (_u *ClientAppUpdateOne) SetAllowedGrantTypes(v []string) *ClientAppUpdateOne {
	_u.mutation.SetAllowedGrantTypes(v)
	return _u
}

// AppendAllowedGrantTypes appends value to the "allowed_grant_types" field.
func (_u *ClientAppUpdateOne) AppendAllowedGrantTypes(v []string) *ClientAppUpdateOne {
	_u.mutation.AppendAllowedGrantTypes(v)
	return _u
}

// ClearAllowedGrantTypes clears the value of the "allowed_grant_types" field.
func (_u *ClientAppUpdateOne) ClearAllowedGrantTypes() *ClientAppUpdateOne {
	_u.mutation.ClearAllowedGrantTypes()
	return _u
}

// SetAllowedScopes sets the "allowed_scopes" field.
func (_u *ClientAppUpdateOne) SetAllowedScopes(v []string) *ClientAppUpdateOne {
	_u.mutation.SetAllowedScopes(v)
	return _u
}

// AppendAllowedScopes appends value to the "allowed_scopes" field.
func (_u *ClientAppUpdateOne) AppendAllowedScopes(v []string) *ClientAppUpdateOne {
	_u.mutation.AppendAllowedScopes(v)
	return _u
}

// ClearAllowedScopes clears the value of the "allowed_scopes" field.
func (_u *ClientAppUpdateOne) ClearAllowedScopes() *ClientAppUpdateOne {
	_u.mutation.ClearAllowedScopes()
	return _u
}

// SetTokenEndpointAuthMethod sets the "token_endpoint_auth_method" field.
func (_u *ClientAppUpdateOne) SetTokenEndpointAuthMethod(v string) *ClientAppUpdateOne {
	_u.mutation.SetTokenEndpointAuthMethod(v)
	return _u
}

// SetNillableTokenEndpointAuthMethod sets the "token_endpoint_auth_method" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableTokenEndpointAuthMethod(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetTokenEndpointAuthMethod(*v)
	}
	return _u
}

// ClearTokenEndpointAuthMethod clears the value of the "token_endpoint_auth_method" field.
func (_u *ClientAppUpdateOne) ClearTokenEndpointAuthMethod() *ClientAppUpdateOne {
	_u.mutation.ClearTokenEndpointAuthMethod()
	return _u
}

// SetIDTokenSignedAlg sets the "id_token_signed_alg" field.
func (_u *ClientAppUpdateOne) SetIDTokenSignedAlg(v string) *ClientAppUpdateOne {
	_u.mutation.SetIDTokenSignedAlg(v)
	return _u
}

// SetNillableIDTokenSignedAlg sets the "id_token_signed_alg" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableIDTokenSignedAlg(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetIDTokenSignedAlg(*v)
	}
	return _u
}

// ClearIDTokenSignedAlg clears the value of the "id_token_signed_alg" field.
func (_u *ClientAppUpdateOne) ClearIDTokenSignedAlg() *ClientAppUpdateOne {
	_u.mutation.ClearIDTokenSignedAlg()
	return _u
}

// SetAccessTokenTTL sets the "access_token_ttl" field.
func (_u *ClientAppUpdateOne) SetAccessTokenTTL(v int) *ClientAppUpdateOne {
	_u.mutation.ResetAccessTokenTTL()
	_u.mutation.SetAccessTokenTTL(v)
	return _u
}

// SetNillableAccessTokenTTL sets the "access_token_ttl" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableAccessTokenTTL(v *int) *ClientAppUpdateOne {
	if v != nil {
		_u.SetAccessTokenTTL(*v)
	}
	return _u
}

// AddAccessTokenTTL adds value to the "access_token_ttl" field.
func (_u *ClientAppUpdateOne) AddAccessTokenTTL(v int) *ClientAppUpdateOne {
	_u.mutation.AddAccessTokenTTL(v)
	return _u
}

// SetRefreshTokenTTL sets the "refresh_token_ttl" field.
func (_u *ClientAppUpdateOne) SetRefreshTokenTTL(v int) *ClientAppUpdateOne {
	_u.mutation.ResetRefreshTokenTTL()
	_u.mutation.SetRefreshTokenTTL(v)
	return _u
}

// SetNillableRefreshTokenTTL sets the "refresh_token_ttl" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableRefreshTokenTTL(v *int) *ClientAppUpdateOne {
	if v != nil {
		_u.SetRefreshTokenTTL(*v)
	}
	return _u
}

// AddRefreshTokenTTL adds value to the "refresh_token_ttl" field.
func (_u *ClientAppUpdateOne) AddRefreshTokenTTL(v int) *ClientAppUpdateOne {
	_u.mutation.AddRefreshTokenTTL(v)
	return _u
}

// SetIDTokenTTL sets the "id_token_ttl" field.
func (_u *ClientAppUpdateOne) SetIDTokenTTL(v int) *ClientAppUpdateOne {
	_u.mutation.ResetIDTokenTTL()
	_u.mutation.SetIDTokenTTL(v)
	return _u
}

// SetNillableIDTokenTTL sets the "id_token_ttl" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableIDTokenTTL(v *int) *ClientAppUpdateOne {
	if v != nil {
		_u.SetIDTokenTTL(*v)
	}
	return _u
}

// AddIDTokenTTL adds value to the "id_token_ttl" field.
func (_u *ClientAppUpdateOne) AddIDTokenTTL(v int) *ClientAppUpdateOne {
	_u.mutation.AddIDTokenTTL(v)
	return _u
}

// SetRequirePkce sets the "require_pkce" field.
func (_u *ClientAppUpdateOne) SetRequirePkce(v bool) *ClientAppUpdateOne {
	_u.mutation.SetRequirePkce(v)
	return _u
}

// SetNillableRequirePkce sets the "require_pkce" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableRequirePkce(v *bool) *ClientAppUpdateOne {
	if v != nil {
		_u.SetRequirePkce(*v)
	}
	return _u
}

// SetEntityID sets the "entity_id" field.
func (_u *ClientAppUpdateOne) SetEntityID(v string) *ClientAppUpdateOne {
	_u.mutation.SetEntityID(v)
	return _u
}

// SetNillableEntityID sets the "entity_id" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableEntityID(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetEntityID(*v)
	}
	return _u
}

// ClearEntityID clears the value of the "entity_id" field.
func (_u *ClientAppUpdateOne) ClearEntityID() *ClientAppUpdateOne {
	_u.mutation.ClearEntityID()
	return _u
}

// SetAcsURL sets the "acs_url" field.
func (_u *ClientAppUpdateOne) SetAcsURL(v string) *ClientAppUpdateOne {
	_u.mutation.SetAcsURL(v)
	return _u
}

// SetNillableAcsURL sets the "acs_url" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableAcsURL(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetAcsURL(*v)
	}
	return _u
}

// ClearAcsURL clears the value of the "acs_url" field.
func (_u *ClientAppUpdateOne) ClearAcsURL() *ClientAppUpdateOne {
	_u.mutation.ClearAcsURL()
	return _u
}

// SetSloURL sets the "slo_url" field.
func (_u *ClientAppUpdateOne) SetSloURL(v string) *ClientAppUpdateOne {
	_u.mutation.SetSloURL(v)
	return _u
}

// SetNillableSloURL sets the "slo_url" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableSloURL(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetSloURL(*v)
	}
	return _u
}

// ClearSloURL clears the value of the "slo_url" field.
func (_u *ClientAppUpdateOne) ClearSloURL() *ClientAppUpdateOne {
	_u.mutation.ClearSloURL()
	return _u
}

// SetClientCertificates sets the "client_certificates" field.
func (_u *ClientAppUpdateOne) SetClientCertificates(v []map[string]interface{}) *ClientAppUpdateOne {
	_u.mutation.SetClientCertificates(v)
	return _u
}

// AppendClientCertificates appends value to the "client_certificates" field.
func (_u *ClientAppUpdateOne) AppendClientCertificates(v []map[string]interface{}) *ClientAppUpdateOne {
	_u.mutation.AppendClientCertificates(v)
	return _u
}

// ClearClientCertificates clears the value of the "client_certificates" field.
func (_u *ClientAppUpdateOne) ClearClientCertificates() *ClientAppUpdateOne {
	_u.mutation.ClearClientCertificates()
	return _u
}

// SetNameIDFormat sets the "name_id_format" field.
func (_u *ClientAppUpdateOne) SetNameIDFormat(v string) *ClientAppUpdateOne {
	_u.mutation.SetNameIDFormat(v)
	return _u
}

// SetNillableNameIDFormat sets the "name_id_format" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableNameIDFormat(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetNameIDFormat(*v)
	}
	return _u
}

// ClearNameIDFormat clears the value of the "name_id_format" field.
func (_u *ClientAppUpdateOne) ClearNameIDFormat() *ClientAppUpdateOne {
	_u.mutation.ClearNameIDFormat()
	return _u
}

// SetWantAssertionSigned sets the "want_assertion_signed" field.
func (_u *ClientAppUpdateOne) SetWantAssertionSigned(v bool) *ClientAppUpdateOne {
	_u.mutation.SetWantAssertionSigned(v)
	return _u
}

// SetNillableWantAssertionSigned sets the "want_assertion_signed" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableWantAssertionSigned(v *bool) *ClientAppUpdateOne {
	if v != nil {
		_u.SetWantAssertionSigned(*v)
	}
	return _u
}

// SetWantResponseSigned sets the "want_response_signed" field.
func (_u *ClientAppUpdateOne) SetWantResponseSigned(v bool) *ClientAppUpdateOne {
	_u.mutation.SetWantResponseSigned(v)
	return _u
}

// SetNillableWantResponseSigned sets the "want_response_signed" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableWantResponseSigned(v *bool) *ClientAppUpdateOne {
	if v != nil {
		_u.SetWantResponseSigned(*v)
	}
	return _u
}

// SetDefaultRelayState sets the "default_relay_state" field.
func (_u *ClientAppUpdateOne) SetDefaultRelayState(v string) *ClientAppUpdateOne {
	_u.mutation.SetDefaultRelayState(v)
	return _u
}

// SetNillableDefaultRelayState sets the "default_relay_state" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableDefaultRelayState(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetDefaultRelayState(*v)
	}
	return _u
}

// ClearDefaultRelayState clears the value of the "default_relay_state" field.
func (_u *ClientAppUpdateOne) ClearDefaultRelayState() *ClientAppUpdateOne {
	_u.mutation.ClearDefaultRelayState()
	return _u
}

// SetAttributeMappings sets the "attribute_mappings" field.
func (_u *ClientAppUpdateOne) SetAttributeMappings(v map[string]interface{}) *ClientAppUpdateOne {
	_u.mutation.SetAttributeMappings(v)
	return _u
}

// ClearAttributeMappings clears the value of the "attribute_mappings" field.
func (_u *ClientAppUpdateOne) ClearAttributeMappings() *ClientAppUpdateOne {
	_u.mutation.ClearAttributeMappings()
	return _u
}

// SetRequireConsent sets the "require_consent" field.
func (_u *ClientAppUpdateOne) SetRequireConsent(v bool) *ClientAppUpdateOne {
	_u.mutation.SetRequireConsent(v)
	return _u
}

// SetNillableRequireConsent sets the "require_consent" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableRequireConsent(v *bool) *ClientAppUpdateOne {
	if v != nil {
		_u.SetRequireConsent(*v)
	}
	return _u
}

// SetMetadataURL sets the "metadata_url" field.
func (_u *ClientAppUpdateOne) SetMetadataURL(v string) *ClientAppUpdateOne {
	_u.mutation.SetMetadataURL(v)
	return _u
}

// SetNillableMetadataURL sets the "metadata_url" field if the given value is not nil.
func (_u *ClientAppUpdateOne) SetNillableMetadataURL(v *string) *ClientAppUpdateOne {
	if v != nil {
		_u.SetMetadataURL(*v)
	}
	return _u
}

// ClearMetadataURL clears the value of the "metadata_url" field.
func (_u *ClientAppUpdateOne) ClearMetadataURL() *ClientAppUpdateOne {
	_u.mutation.ClearMetadataURL()
	return _u
}

// AddRoleIDs adds the "roles" edge to the Role entity by IDs.
func (_u *ClientAppUpdateOne) AddRoleIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.AddRoleIDs(ids...)
	return _u
}

// AddRoles adds the "roles" edges to the Role entity.
func (_u *ClientAppUpdateOne) AddRoles(v ...*Role) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoleIDs(ids...)
}

// AddGroupIDs adds the "groups" edge to the Group entity by IDs.
func (_u *ClientAppUpdateOne) AddGroupIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.AddGroupIDs(ids...)
	return _u
}

// AddGroups adds the "groups" edges to the Group entity.
func (_u *ClientAppUpdateOne) AddGroups(v ...*Group) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGroupIDs(ids...)
}

// AddClientScopeIDs adds the "client_scopes" edge to the ClientScope entity by IDs.
func (_u *ClientAppUpdateOne) AddClientScopeIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.AddClientScopeIDs(ids...)
	return _u
}

// AddClientScopes adds the "client_scopes" edges to the ClientScope entity.
func (_u *ClientAppUpdateOne) AddClientScopes(v ...*ClientScope) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientScopeIDs(ids...)
}

// AddTokenIDs adds the "tokens" edge to the Token entity by IDs.
func (_u *ClientAppUpdateOne) AddTokenIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.AddTokenIDs(ids...)
	return _u
}

// AddTokens adds the "tokens" edges to the Token entity.
func (_u *ClientAppUpdateOne) AddTokens(v ...*Token) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTokenIDs(ids...)
}

// AddConsentIDs adds the "consents" edge to the Consent entity by IDs.
func (_u *ClientAppUpdateOne) AddConsentIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.AddConsentIDs(ids...)
	return _u
}

// AddConsents adds the "consents" edges to the Consent entity.
func (_u *ClientAppUpdateOne) AddConsents(v ...*Consent) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConsentIDs(ids...)
}

// AddClientRoleIDs adds the "client_roles" edge to the ClientRole entity by IDs.
func (_u *ClientAppUpdateOne) AddClientRoleIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.AddClientRoleIDs(ids...)
	return _u
}

// AddClientRoles adds the "client_roles" edges to the ClientRole entity.
func (_u *ClientAppUpdateOne) AddClientRoles(v ...*ClientRole) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientRoleIDs(ids...)
}

// AddClientGroupIDs adds the "client_groups" edge to the ClientGroup entity by IDs.
func (_u *ClientAppUpdateOne) AddClientGroupIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.AddClientGroupIDs(ids...)
	return _u
}

// AddClientGroups adds the "client_groups" edges to the ClientGroup entity.
func (_u *ClientAppUpdateOne) AddClientGroups(v ...*ClientGroup) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientGroupIDs(ids...)
}

// AddClientScopeMappingIDs adds the "client_scope_mappings" edge to the ClientScopeMapping entity by IDs.
func (_u *ClientAppUpdateOne) AddClientScopeMappingIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.AddClientScopeMappingIDs(ids...)
	return _u
}

// AddClientScopeMappings adds the "client_scope_mappings" edges to the ClientScopeMapping entity.
func (_u *ClientAppUpdateOne) AddClientScopeMappings(v ...*ClientScopeMapping) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientScopeMappingIDs(ids...)
}

// Mutation returns the ClientAppMutation object of the builder.
func (_u *ClientAppUpdateOne) Mutation() *ClientAppMutation {
	return _u.mutation
}

// ClearRoles clears all "roles" edges to the Role entity.
func (_u *ClientAppUpdateOne) ClearRoles() *ClientAppUpdateOne {
	_u.mutation.ClearRoles()
	return _u
}

// RemoveRoleIDs removes the "roles" edge to Role entities by IDs.
func (_u *ClientAppUpdateOne) RemoveRoleIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.RemoveRoleIDs(ids...)
	return _u
}

// RemoveRoles removes "roles" edges to Role entities.
func (_u *ClientAppUpdateOne) RemoveRoles(v ...*Role) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoleIDs(ids...)
}

// ClearGroups clears all "groups" edges to the Group entity.
func (_u *ClientAppUpdateOne) ClearGroups() *ClientAppUpdateOne {
	_u.mutation.ClearGroups()
	return _u
}

// RemoveGroupIDs removes the "groups" edge to Group entities by IDs.
func (_u *ClientAppUpdateOne) RemoveGroupIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.RemoveGroupIDs(ids...)
	return _u
}

// RemoveGroups removes "groups" edges to Group entities.
func (_u *ClientAppUpdateOne) RemoveGroups(v ...*Group) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGroupIDs(ids...)
}

// ClearClientScopes clears all "client_scopes" edges to the ClientScope entity.
func (_u *ClientAppUpdateOne) ClearClientScopes() *ClientAppUpdateOne {
	_u.mutation.ClearClientScopes()
	return _u
}

// RemoveClientScopeIDs removes the "client_scopes" edge to ClientScope entities by IDs.
func (_u *ClientAppUpdateOne) RemoveClientScopeIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.RemoveClientScopeIDs(ids...)
	return _u
}

// RemoveClientScopes removes "client_scopes" edges to ClientScope entities.
func (_u *ClientAppUpdateOne) RemoveClientScopes(v ...*ClientScope) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientScopeIDs(ids...)
}

// ClearTokens clears all "tokens" edges to the Token entity.
func (_u *ClientAppUpdateOne) ClearTokens() *ClientAppUpdateOne {
	_u.mutation.ClearTokens()
	return _u
}

// RemoveTokenIDs removes the "tokens" edge to Token entities by IDs.
func (_u *ClientAppUpdateOne) RemoveTokenIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.RemoveTokenIDs(ids...)
	return _u
}

// RemoveTokens removes "tokens" edges to Token entities.
func (_u *ClientAppUpdateOne) RemoveTokens(v ...*Token) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTokenIDs(ids...)
}

// ClearConsents clears all "consents" edges to the Consent entity.
func (_u *ClientAppUpdateOne) ClearConsents() *ClientAppUpdateOne {
	_u.mutation.ClearConsents()
	return _u
}

// RemoveConsentIDs removes the "consents" edge to Consent entities by IDs.
func (_u *ClientAppUpdateOne) RemoveConsentIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.RemoveConsentIDs(ids...)
	return _u
}

// RemoveConsents removes "consents" edges to Consent entities.
func (_u *ClientAppUpdateOne) RemoveConsents(v ...*Consent) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConsentIDs(ids...)
}

// ClearClientRoles clears all "client_roles" edges to the ClientRole entity.
func (_u *ClientAppUpdateOne) ClearClientRoles() *ClientAppUpdateOne {
	_u.mutation.ClearClientRoles()
	return _u
}

// RemoveClientRoleIDs removes the "client_roles" edge to ClientRole entities by IDs.
func (_u *ClientAppUpdateOne) RemoveClientRoleIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.RemoveClientRoleIDs(ids...)
	return _u
}

// RemoveClientRoles removes "client_roles" edges to ClientRole entities.
func (_u *ClientAppUpdateOne) RemoveClientRoles(v ...*ClientRole) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientRoleIDs(ids...)
}

// ClearClientGroups clears all "client_groups" edges to the ClientGroup entity.
func (_u *ClientAppUpdateOne) ClearClientGroups() *ClientAppUpdateOne {
	_u.mutation.ClearClientGroups()
	return _u
}

// RemoveClientGroupIDs removes the "client_groups" edge to ClientGroup entities by IDs.
func (_u *ClientAppUpdateOne) RemoveClientGroupIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.RemoveClientGroupIDs(ids...)
	return _u
}

// RemoveClientGroups removes "client_groups" edges to ClientGroup entities.
func (_u *ClientAppUpdateOne) RemoveClientGroups(v ...*ClientGroup) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientGroupIDs(ids...)
}

// ClearClientScopeMappings clears all "client_scope_mappings" edges to the ClientScopeMapping entity.
func (_u *ClientAppUpdateOne) ClearClientScopeMappings() *ClientAppUpdateOne {
	_u.mutation.ClearClientScopeMappings()
	return _u
}

// RemoveClientScopeMappingIDs removes the "client_scope_mappings" edge to ClientScopeMapping entities by IDs.
func (_u *ClientAppUpdateOne) RemoveClientScopeMappingIDs(ids ...string) *ClientAppUpdateOne {
	_u.mutation.RemoveClientScopeMappingIDs(ids...)
	return _u
}

// RemoveClientScopeMappings removes "client_scope_mappings" edges to ClientScopeMapping entities.
func (_u *ClientAppUpdateOne) RemoveClientScopeMappings(v ...*ClientScopeMapping) *ClientAppUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientScopeMappingIDs(ids...)
}

// Where appends a list predicates to the ClientAppUpdate builder.
func (_u *ClientAppUpdateOne) Where(ps ...predicate.ClientApp) *ClientAppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClientAppUpdateOne) Select(field string, fields ...string) *ClientAppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ClientApp entity.
func (_u *ClientAppUpdateOne) Save(ctx context.Context) (*ClientApp, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClientAppUpdateOne) SaveX(ctx context.Context) *ClientApp {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClientAppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClientAppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClientAppUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := clientapp.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClientAppUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := clientapp.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientApp.name": %w`, err)}
		}
	}
	if _u.mutation.RealmCleared() && len(_u.mutation.RealmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ClientApp.realm"`)
	}
	return nil
}

func (_u *ClientAppUpdateOne) sqlSave(ctx context.Context) (_node *ClientApp, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clientapp.Table, clientapp.Columns, sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClientApp.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clientapp.FieldID)
		for _, f := range fields {
			if !clientapp.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clientapp.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ManagedBy(); ok {
		_spec.SetField(clientapp.FieldManagedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(clientapp.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(clientapp.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(clientapp.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(clientapp.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(clientapp.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OwnerAdminID(); ok {
		_spec.SetField(clientapp.FieldOwnerAdminID, field.TypeString, value)
	}
	if _u.mutation.OwnerAdminIDCleared() {
		_spec.ClearField(clientapp.FieldOwnerAdminID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(clientapp.FieldClientID, field.TypeString, value)
	}
	if _u.mutation.ClientIDCleared() {
		_spec.ClearField(clientapp.FieldClientID, field.TypeString)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(clientapp.FieldClientSecretHash, field.TypeString, value)
	}
	if _u.mutation.ClientSecretHashCleared() {
		_spec.ClearField(clientapp.FieldClientSecretHash, field.TypeString)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(clientapp.FieldClientType, field.TypeString, value)
	}
	if _u.mutation.ClientTypeCleared() {
		_spec.ClearField(clientapp.FieldClientType, field.TypeString)
	}
	if value, ok := _u.mutation.RedirectUris(); ok {
		_spec.SetField(clientapp.FieldRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldRedirectUris, value)
		})
	}
	if _u.mutation.RedirectUrisCleared() {
		_spec.ClearField(clientapp.FieldRedirectUris, field.TypeJSON)
	}
	if value, ok := _u.mutation.PostLogoutRedirectUris(); ok {
		_spec.SetField(clientapp.FieldPostLogoutRedirectUris, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPostLogoutRedirectUris(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldPostLogoutRedirectUris, value)
		})
	}
	if _u.mutation.PostLogoutRedirectUrisCleared() {
		_spec.ClearField(clientapp.FieldPostLogoutRedirectUris, field.TypeJSON)
	}
	if value, ok := _u.mutation.AllowedGrantTypes(); ok {
		_spec.SetField(clientapp.FieldAllowedGrantTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedGrantTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldAllowedGrantTypes, value)
		})
	}
	if _u.mutation.AllowedGrantTypesCleared() {
		_spec.ClearField(clientapp.FieldAllowedGrantTypes, field.TypeJSON)
	}
	if value, ok := _u.mutation.AllowedScopes(); ok {
		_spec.SetField(clientapp.FieldAllowedScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAllowedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldAllowedScopes, value)
		})
	}
	if _u.mutation.AllowedScopesCleared() {
		_spec.ClearField(clientapp.FieldAllowedScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.TokenEndpointAuthMethod(); ok {
		_spec.SetField(clientapp.FieldTokenEndpointAuthMethod, field.TypeString, value)
	}
	if _u.mutation.TokenEndpointAuthMethodCleared() {
		_spec.ClearField(clientapp.FieldTokenEndpointAuthMethod, field.TypeString)
	}
	if value, ok := _u.mutation.IDTokenSignedAlg(); ok {
		_spec.SetField(clientapp.FieldIDTokenSignedAlg, field.TypeString, value)
	}
	if _u.mutation.IDTokenSignedAlgCleared() {
		_spec.ClearField(clientapp.FieldIDTokenSignedAlg, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenTTL(); ok {
		_spec.SetField(clientapp.FieldAccessTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessTokenTTL(); ok {
		_spec.AddField(clientapp.FieldAccessTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefreshTokenTTL(); ok {
		_spec.SetField(clientapp.FieldRefreshTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshTokenTTL(); ok {
		_spec.AddField(clientapp.FieldRefreshTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IDTokenTTL(); ok {
		_spec.SetField(clientapp.FieldIDTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIDTokenTTL(); ok {
		_spec.AddField(clientapp.FieldIDTokenTTL, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequirePkce(); ok {
		_spec.SetField(clientapp.FieldRequirePkce, field.TypeBool, value)
	}
	if value, ok := _u.mutation.EntityID(); ok {
		_spec.SetField(clientapp.FieldEntityID, field.TypeString, value)
	}
	if _u.mutation.EntityIDCleared() {
		_spec.ClearField(clientapp.FieldEntityID, field.TypeString)
	}
	if value, ok := _u.mutation.AcsURL(); ok {
		_spec.SetField(clientapp.FieldAcsURL, field.TypeString, value)
	}
	if _u.mutation.AcsURLCleared() {
		_spec.ClearField(clientapp.FieldAcsURL, field.TypeString)
	}
	if value, ok := _u.mutation.SloURL(); ok {
		_spec.SetField(clientapp.FieldSloURL, field.TypeString, value)
	}
	if _u.mutation.SloURLCleared() {
		_spec.ClearField(clientapp.FieldSloURL, field.TypeString)
	}
	if value, ok := _u.mutation.ClientCertificates(); ok {
		_spec.SetField(clientapp.FieldClientCertificates, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedClientCertificates(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, clientapp.FieldClientCertificates, value)
		})
	}
	if _u.mutation.ClientCertificatesCleared() {
		_spec.ClearField(clientapp.FieldClientCertificates, field.TypeJSON)
	}
	if value, ok := _u.mutation.NameIDFormat(); ok {
		_spec.SetField(clientapp.FieldNameIDFormat, field.TypeString, value)
	}
	if _u.mutation.NameIDFormatCleared() {
		_spec.ClearField(clientapp.FieldNameIDFormat, field.TypeString)
	}
	if value, ok := _u.mutation.WantAssertionSigned(); ok {
		_spec.SetField(clientapp.FieldWantAssertionSigned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.WantResponseSigned(); ok {
		_spec.SetField(clientapp.FieldWantResponseSigned, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DefaultRelayState(); ok {
		_spec.SetField(clientapp.FieldDefaultRelayState, field.TypeString, value)
	}
	if _u.mutation.DefaultRelayStateCleared() {
		_spec.ClearField(clientapp.FieldDefaultRelayState, field.TypeString)
	}
	if value, ok := _u.mutation.AttributeMappings(); ok {
		_spec.SetField(clientapp.FieldAttributeMappings, field.TypeJSON, value)
	}
	if _u.mutation.AttributeMappingsCleared() {
		_spec.ClearField(clientapp.FieldAttributeMappings, field.TypeJSON)
	}
	if value, ok := _u.mutation.RequireConsent(); ok {
		_spec.SetField(clientapp.FieldRequireConsent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MetadataURL(); ok {
		_spec.SetField(clientapp.FieldMetadataURL, field.TypeString, value)
	}
	if _u.mutation.MetadataURLCleared() {
		_spec.ClearField(clientapp.FieldMetadataURL, field.TypeString)
	}
	if _u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.RolesTable,
			Columns: clientapp.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		createE := &ClientRoleCreate{config: _u.config, mutation: newClientRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRolesIDs(); len(nodes) > 0 && !_u.mutation.RolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.RolesTable,
			Columns: clientapp.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientRoleCreate{config: _u.config, mutation: newClientRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.RolesTable,
			Columns: clientapp.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientRoleCreate{config: _u.config, mutation: newClientRoleMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.GroupsTable,
			Columns: clientapp.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		createE := &ClientGroupCreate{config: _u.config, mutation: newClientGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGroupsIDs(); len(nodes) > 0 && !_u.mutation.GroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.GroupsTable,
			Columns: clientapp.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientGroupCreate{config: _u.config, mutation: newClientGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   clientapp.GroupsTable,
			Columns: clientapp.GroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientGroupCreate{config: _u.config, mutation: newClientGroupMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientapp.ClientScopesTable,
			Columns: clientapp.ClientScopesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscope.FieldID, field.TypeString),
			},
		}
		createE := &ClientScopeMappingCreate{config: _u.config, mutation: newClientScopeMappingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientScopesIDs(); len(nodes) > 0 && !_u.mutation.ClientScopesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientapp.ClientScopesTable,
			Columns: clientapp.ClientScopesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscope.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientScopeMappingCreate{config: _u.config, mutation: newClientScopeMappingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientScopesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   clientapp.ClientScopesTable,
			Columns: clientapp.ClientScopesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscope.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ClientScopeMappingCreate{config: _u.config, mutation: newClientScopeMappingMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		if specE.ID.Value != nil {
			edge.Target.Fields = append(edge.Target.Fields, specE.ID)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.TokensTable,
			Columns: []string{clientapp.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(token.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTokensIDs(); len(nodes) > 0 && !_u.mutation.TokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.TokensTable,
			Columns: []string{clientapp.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(token.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.TokensTable,
			Columns: []string{clientapp.TokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(token.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.ConsentsTable,
			Columns: []string{clientapp.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consent.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConsentsIDs(); len(nodes) > 0 && !_u.mutation.ConsentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.ConsentsTable,
			Columns: []string{clientapp.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.ConsentsTable,
			Columns: []string{clientapp.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(consent.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientRolesTable,
			Columns: []string{clientapp.ClientRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientrole.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientRolesIDs(); len(nodes) > 0 && !_u.mutation.ClientRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientRolesTable,
			Columns: []string{clientapp.ClientRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientrole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientRolesTable,
			Columns: []string{clientapp.ClientRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientrole.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientGroupsTable,
			Columns: []string{clientapp.ClientGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientgroup.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientGroupsIDs(); len(nodes) > 0 && !_u.mutation.ClientGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientGroupsTable,
			Columns: []string{clientapp.ClientGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientgroup.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientGroupsTable,
			Columns: []string{clientapp.ClientGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientgroup.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ClientScopeMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientScopeMappingsTable,
			Columns: []string{clientapp.ClientScopeMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscopemapping.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientScopeMappingsIDs(); len(nodes) > 0 && !_u.mutation.ClientScopeMappingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientScopeMappingsTable,
			Columns: []string{clientapp.ClientScopeMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscopemapping.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientScopeMappingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   clientapp.ClientScopeMappingsTable,
			Columns: []string{clientapp.ClientScopeMappingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientscopemapping.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ClientApp{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clientapp.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
