// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"sso.internal/sso/ent/clientapp"
	"sso.internal/sso/ent/clientgroup"
	"sso.internal/sso/ent/group"
)

// ClientGroupCreate is the builder for creating a ClientGroup entity.
type ClientGroupCreate struct {
	config
	mutation *ClientGroupMutation
	hooks    []Hook
}

// SetClientAppID sets the "client_app_id" field.
func (_c *ClientGroupCreate) SetClientAppID(v string) *ClientGroupCreate {
	_c.mutation.SetClientAppID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ClientGroupCreate) SetGroupID(v string) *ClientGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetGrantedAt sets the "granted_at" field.
func (_c *ClientGroupCreate) SetGrantedAt(v time.Time) *ClientGroupCreate {
	_c.mutation.SetGrantedAt(v)
	return _c
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_c *ClientGroupCreate) SetNillableGrantedAt(v *time.Time) *ClientGroupCreate {
	if v != nil {
		_c.SetGrantedAt(*v)
	}
	return _c
}

// SetGrantedBy sets the "granted_by" field.
func (_c *ClientGroupCreate) SetGrantedBy(v string) *ClientGroupCreate {
	_c.mutation.SetGrantedBy(v)
	return _c
}

// SetNillableGrantedBy sets the "granted_by" field if the given value is not nil.
func (_c *ClientGroupCreate) SetNillableGrantedBy(v *string) *ClientGroupCreate {
	if v != nil {
		_c.SetGrantedBy(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ClientGroupCreate) SetID(v string) *ClientGroupCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ClientGroupCreate) SetNillableID(v *string) *ClientGroupCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetClientApp sets the "client_app" edge to the ClientApp entity.
func (_c *ClientGroupCreate) SetClientApp(v *ClientApp) *ClientGroupCreate {
	return _c.SetClientAppID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *ClientGroupCreate) SetGroup(v *Group) *ClientGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the ClientGroupMutation object of the builder.
func (_c *ClientGroupCreate) Mutation() *ClientGroupMutation {
	return _c.mutation
}

// Save creates the ClientGroup in the database.
func (_c *ClientGroupCreate) Save(ctx context.Context) (*ClientGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClientGroupCreate) SaveX(ctx context.Context) *ClientGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClientGroupCreate) defaults() {
	if _, ok := _c.mutation.GrantedAt(); !ok {
		v := clientgroup.DefaultGrantedAt()
		_c.mutation.SetGrantedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := clientgroup.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClientGroupCreate) check() error {
	if _, ok := _c.mutation.ClientAppID(); !ok {
		return &ValidationError{Name: "client_app_id", err: errors.New(`ent: missing required field "ClientGroup.client_app_id"`)}
	}
	if v, ok := _c.mutation.ClientAppID(); ok {
		if err := clientgroup.ClientAppIDValidator(v); err != nil {
			return &ValidationError{Name: "client_app_id", err: fmt.Errorf(`ent: validator failed for field "ClientGroup.client_app_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "ClientGroup.group_id"`)}
	}
	if v, ok := _c.mutation.GroupID(); ok {
		if err := clientgroup.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "ClientGroup.group_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		return &ValidationError{Name: "granted_at", err: errors.New(`ent: missing required field "ClientGroup.granted_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := clientgroup.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ClientGroup.id": %w`, err)}
		}
	}
	if len(_c.mutation.ClientAppIDs()) == 0 {
		return &ValidationError{Name: "client_app", err: errors.New(`ent: missing required edge "ClientGroup.client_app"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "ClientGroup.group"`)}
	}
	return nil
}

func (_c *ClientGroupCreate) sqlSave(ctx context.Context) (*ClientGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ClientGroup.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClientGroupCreate) createSpec() (*ClientGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &ClientGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clientgroup.Table, sqlgraph.NewFieldSpec(clientgroup.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GrantedAt(); ok {
		_spec.SetField(clientgroup.FieldGrantedAt, field.TypeTime, value)
		_node.GrantedAt = value
	}
	if value, ok := _c.mutation.GrantedBy(); ok {
		_spec.SetField(clientgroup.FieldGrantedBy, field.TypeString, value)
		_node.GrantedBy = value
	}
	if nodes := _c.mutation.ClientAppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   clientgroup.ClientAppTable,
			Columns: []string{clientgroup.ClientAppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClientAppID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   clientgroup.GroupTable,
			Columns: []string{clientgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClientGroupCreateBulk is the builder for creating many ClientGroup entities in bulk.
type ClientGroupCreateBulk struct {
	config
	err      error
	builders []*ClientGroupCreate
}

// Save creates the ClientGroup entities in the database.
func (_c *ClientGroupCreateBulk) Save(ctx context.Context) ([]*ClientGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ClientGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClientGroupCreateBulk) SaveX(ctx context.Context) []*ClientGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
