// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"sso.internal/sso/ent/federatedidentity"
	"sso.internal/sso/ent/identityprovider"
	"sso.internal/sso/ent/realm"
	"sso.internal/sso/ent/schema"
)

// IdentityProviderCreate is the builder for creating a IdentityProvider entity.
type IdentityProviderCreate struct {
	config
	mutation *IdentityProviderMutation
	hooks    []Hook
}

// SetRealmID sets the "realm_id" field.
func (_c *IdentityProviderCreate) SetRealmID(v string) *IdentityProviderCreate {
	_c.mutation.SetRealmID(v)
	return _c
}

// SetManagedBy sets the "managed_by" field.
func (_c *IdentityProviderCreate) SetManagedBy(v schema.IdentityProviderManagedBy) *IdentityProviderCreate {
	_c.mutation.SetManagedBy(v)
	return _c
}

// SetNillableManagedBy sets the "managed_by" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableManagedBy(v *schema.IdentityProviderManagedBy) *IdentityProviderCreate {
	if v != nil {
		_c.SetManagedBy(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *IdentityProviderCreate) SetName(v string) *IdentityProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *IdentityProviderCreate) SetProtocol(v schema.IdentityProviderProtocol) *IdentityProviderCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *IdentityProviderCreate) SetStatus(v schema.IdentityProviderStatus) *IdentityProviderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableStatus(v *schema.IdentityProviderStatus) *IdentityProviderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IdentityProviderCreate) SetCreatedAt(v time.Time) *IdentityProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableCreatedAt(v *time.Time) *IdentityProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IdentityProviderCreate) SetUpdatedAt(v time.Time) *IdentityProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableUpdatedAt(v *time.Time) *IdentityProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetIssuerURL sets the "issuer_url" field.
func (_c *IdentityProviderCreate) SetIssuerURL(v string) *IdentityProviderCreate {
	_c.mutation.SetIssuerURL(v)
	return _c
}

// SetNillableIssuerURL sets the "issuer_url" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableIssuerURL(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetIssuerURL(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *IdentityProviderCreate) SetClientID(v string) *IdentityProviderCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableClientID(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetClientID(*v)
	}
	return _c
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_c *IdentityProviderCreate) SetClientSecretHash(v string) *IdentityProviderCreate {
	_c.mutation.SetClientSecretHash(v)
	return _c
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableClientSecretHash(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetClientSecretHash(*v)
	}
	return _c
}

// SetAuthorizationEndpoint sets the "authorization_endpoint" field.
func (_c *IdentityProviderCreate) SetAuthorizationEndpoint(v string) *IdentityProviderCreate {
	_c.mutation.SetAuthorizationEndpoint(v)
	return _c
}

// SetNillableAuthorizationEndpoint sets the "authorization_endpoint" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableAuthorizationEndpoint(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetAuthorizationEndpoint(*v)
	}
	return _c
}

// SetTokenEndpoint sets the "token_endpoint" field.
func (_c *IdentityProviderCreate) SetTokenEndpoint(v string) *IdentityProviderCreate {
	_c.mutation.SetTokenEndpoint(v)
	return _c
}

// SetNillableTokenEndpoint sets the "token_endpoint" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableTokenEndpoint(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetTokenEndpoint(*v)
	}
	return _c
}

// SetUserinfoEndpoint sets the "userinfo_endpoint" field.
func (_c *IdentityProviderCreate) SetUserinfoEndpoint(v string) *IdentityProviderCreate {
	_c.mutation.SetUserinfoEndpoint(v)
	return _c
}

// SetNillableUserinfoEndpoint sets the "userinfo_endpoint" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableUserinfoEndpoint(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetUserinfoEndpoint(*v)
	}
	return _c
}

// SetJwksURI sets the "jwks_uri" field.
func (_c *IdentityProviderCreate) SetJwksURI(v string) *IdentityProviderCreate {
	_c.mutation.SetJwksURI(v)
	return _c
}

// SetNillableJwksURI sets the "jwks_uri" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableJwksURI(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetJwksURI(*v)
	}
	return _c
}

// SetScopesRequested sets the "scopes_requested" field.
func (_c *IdentityProviderCreate) SetScopesRequested(v []string) *IdentityProviderCreate {
	_c.mutation.SetScopesRequested(v)
	return _c
}

// SetIdpEntityID sets the "idp_entity_id" field.
func (_c *IdentityProviderCreate) SetIdpEntityID(v string) *IdentityProviderCreate {
	_c.mutation.SetIdpEntityID(v)
	return _c
}

// SetNillableIdpEntityID sets the "idp_entity_id" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableIdpEntityID(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetIdpEntityID(*v)
	}
	return _c
}

// SetIdpSSOURL sets the "idp_sso_url" field.
func (_c *IdentityProviderCreate) SetIdpSSOURL(v string) *IdentityProviderCreate {
	_c.mutation.SetIdpSSOURL(v)
	return _c
}

// SetNillableIdpSSOURL sets the "idp_sso_url" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableIdpSSOURL(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetIdpSSOURL(*v)
	}
	return _c
}

// SetIdpCertificate sets the "idp_certificate" field.
func (_c *IdentityProviderCreate) SetIdpCertificate(v string) *IdentityProviderCreate {
	_c.mutation.SetIdpCertificate(v)
	return _c
}

// SetNillableIdpCertificate sets the "idp_certificate" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableIdpCertificate(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetIdpCertificate(*v)
	}
	return _c
}

// SetAttributeMapping sets the "attribute_mapping" field.
func (_c *IdentityProviderCreate) SetAttributeMapping(v map[string]interface{}) *IdentityProviderCreate {
	_c.mutation.SetAttributeMapping(v)
	return _c
}

// SetAutoProvisioning sets the "auto_provisioning" field.
func (_c *IdentityProviderCreate) SetAutoProvisioning(v bool) *IdentityProviderCreate {
	_c.mutation.SetAutoProvisioning(v)
	return _c
}

// SetNillableAutoProvisioning sets the "auto_provisioning" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableAutoProvisioning(v *bool) *IdentityProviderCreate {
	if v != nil {
		_c.SetAutoProvisioning(*v)
	}
	return _c
}

// SetDefaultRoles sets the "default_roles" field.
func (_c *IdentityProviderCreate) SetDefaultRoles(v []string) *IdentityProviderCreate {
	_c.mutation.SetDefaultRoles(v)
	return _c
}

// SetID sets the "id" field.
func (_c *IdentityProviderCreate) SetID(v string) *IdentityProviderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *IdentityProviderCreate) SetNillableID(v *string) *IdentityProviderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRealm sets the "realm" edge to the Realm entity.
func (_c *IdentityProviderCreate) SetRealm(v *Realm) *IdentityProviderCreate {
	return _c.SetRealmID(v.ID)
}

// AddFederatedIdentityIDs adds the "federated_identities" edge to the FederatedIdentity entity by IDs.
func (_c *IdentityProviderCreate) AddFederatedIdentityIDs(ids ...string) *IdentityProviderCreate {
	_c.mutation.AddFederatedIdentityIDs(ids...)
	return _c
}

// AddFederatedIdentities adds the "federated_identities" edges to the FederatedIdentity entity.
func (_c *IdentityProviderCreate) AddFederatedIdentities(v ...*FederatedIdentity) *IdentityProviderCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFederatedIdentityIDs(ids...)
}

// Mutation returns the IdentityProviderMutation object of the builder.
func (_c *IdentityProviderCreate) Mutation() *IdentityProviderMutation {
	return _c.mutation
}

// Save creates the IdentityProvider in the database.
func (_c *IdentityProviderCreate) Save(ctx context.Context) (*IdentityProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IdentityProviderCreate) SaveX(ctx context.Context) *IdentityProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IdentityProviderCreate) defaults() {
	if _, ok := _c.mutation.ManagedBy(); !ok {
		v := identityprovider.DefaultManagedBy
		_c.mutation.SetManagedBy(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := identityprovider.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := identityprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := identityprovider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AutoProvisioning(); !ok {
		v := identityprovider.DefaultAutoProvisioning
		_c.mutation.SetAutoProvisioning(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := identityprovider.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IdentityProviderCreate) check() error {
	if _, ok := _c.mutation.RealmID(); !ok {
		return &ValidationError{Name: "realm_id", err: errors.New(`ent: missing required field "IdentityProvider.realm_id"`)}
	}
	if v, ok := _c.mutation.RealmID(); ok {
		if err := identityprovider.RealmIDValidator(v); err != nil {
			return &ValidationError{Name: "realm_id", err: fmt.Errorf(`ent: validator failed for field "IdentityProvider.realm_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ManagedBy(); !ok {
		return &ValidationError{Name: "managed_by", err: errors.New(`ent: missing required field "IdentityProvider.managed_by"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "IdentityProvider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := identityprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "IdentityProvider.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "IdentityProvider.protocol"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IdentityProvider.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IdentityProvider.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IdentityProvider.updated_at"`)}
	}
	if _, ok := _c.mutation.AutoProvisioning(); !ok {
		return &ValidationError{Name: "auto_provisioning", err: errors.New(`ent: missing required field "IdentityProvider.auto_provisioning"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := identityprovider.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "IdentityProvider.id": %w`, err)}
		}
	}
	if len(_c.mutation.RealmIDs()) == 0 {
		return &ValidationError{Name: "realm", err: errors.New(`ent: missing required edge "IdentityProvider.realm"`)}
	}
	return nil
}

func (_c *IdentityProviderCreate) sqlSave(ctx context.Context) (*IdentityProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected IdentityProvider.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IdentityProviderCreate) createSpec() (*IdentityProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &IdentityProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(identityprovider.Table, sqlgraph.NewFieldSpec(identityprovider.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ManagedBy(); ok {
		_spec.SetField(identityprovider.FieldManagedBy, field.TypeString, value)
		_node.ManagedBy = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(identityprovider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(identityprovider.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(identityprovider.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(identityprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(identityprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.IssuerURL(); ok {
		_spec.SetField(identityprovider.FieldIssuerURL, field.TypeString, value)
		_node.IssuerURL = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(identityprovider.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecretHash(); ok {
		_spec.SetField(identityprovider.FieldClientSecretHash, field.TypeString, value)
		_node.ClientSecretHash = value
	}
	if value, ok := _c.mutation.AuthorizationEndpoint(); ok {
		_spec.SetField(identityprovider.FieldAuthorizationEndpoint, field.TypeString, value)
		_node.AuthorizationEndpoint = value
	}
	if value, ok := _c.mutation.TokenEndpoint(); ok {
		_spec.SetField(identityprovider.FieldTokenEndpoint, field.TypeString, value)
		_node.TokenEndpoint = value
	}
	if value, ok := _c.mutation.UserinfoEndpoint(); ok {
		_spec.SetField(identityprovider.FieldUserinfoEndpoint, field.TypeString, value)
		_node.UserinfoEndpoint = value
	}
	if value, ok := _c.mutation.JwksURI(); ok {
		_spec.SetField(identityprovider.FieldJwksURI, field.TypeString, value)
		_node.JwksURI = value
	}
	if value, ok := _c.mutation.ScopesRequested(); ok {
		_spec.SetField(identityprovider.FieldScopesRequested, field.TypeJSON, value)
		_node.ScopesRequested = value
	}
	if value, ok := _c.mutation.IdpEntityID(); ok {
		_spec.SetField(identityprovider.FieldIdpEntityID, field.TypeString, value)
		_node.IdpEntityID = value
	}
	if value, ok := _c.mutation.IdpSSOURL(); ok {
		_spec.SetField(identityprovider.FieldIdpSSOURL, field.TypeString, value)
		_node.IdpSSOURL = value
	}
	if value, ok := _c.mutation.IdpCertificate(); ok {
		_spec.SetField(identityprovider.FieldIdpCertificate, field.TypeString, value)
		_node.IdpCertificate = value
	}
	if value, ok := _c.mutation.AttributeMapping(); ok {
		_spec.SetField(identityprovider.FieldAttributeMapping, field.TypeJSON, value)
		_node.AttributeMapping = value
	}
	if value, ok := _c.mutation.AutoProvisioning(); ok {
		_spec.SetField(identityprovider.FieldAutoProvisioning, field.TypeBool, value)
		_node.AutoProvisioning = value
	}
	if value, ok := _c.mutation.DefaultRoles(); ok {
		_spec.SetField(identityprovider.FieldDefaultRoles, field.TypeJSON, value)
		_node.DefaultRoles = value
	}
	if nodes := _c.mutation.RealmIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   identityprovider.RealmTable,
			Columns: []string{identityprovider.RealmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realm.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RealmID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FederatedIdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   identityprovider.FederatedIdentitiesTable,
			Columns: []string{identityprovider.FederatedIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(federatedidentity.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IdentityProviderCreateBulk is the builder for creating many IdentityProvider entities in bulk.
type IdentityProviderCreateBulk struct {
	config
	err      error
	builders []*IdentityProviderCreate
}

// Save creates the IdentityProvider entities in the database.
func (_c *IdentityProviderCreateBulk) Save(ctx context.Context) ([]*IdentityProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IdentityProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdentityProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IdentityProviderCreateBulk) SaveX(ctx context.Context) []*IdentityProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IdentityProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IdentityProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
