// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"sso.internal/sso/ent/instancesettings"
	"sso.internal/sso/ent/realm"
	"sso.internal/sso/ent/schema"
)

// InstanceSettings is the model entity for the InstanceSettings schema.
type InstanceSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// RealmID holds the value of the "realm_id" field.
	RealmID string `json:"realm_id,omitempty"`
	// ManagedBy holds the value of the "managed_by" field.
	ManagedBy schema.InstanceSettingsManagedBy `json:"managed_by,omitempty"`
	// MinPasswordLength holds the value of the "min_password_length" field.
	MinPasswordLength int `json:"min_password_length,omitempty"`
	// PasswordExpiryDays holds the value of the "password_expiry_days" field.
	PasswordExpiryDays int `json:"password_expiry_days,omitempty"`
	// SessionIdleMinutes holds the value of the "session_idle_minutes" field.
	SessionIdleMinutes int `json:"session_idle_minutes,omitempty"`
	// SessionMaxHours holds the value of the "session_max_hours" field.
	SessionMaxHours int `json:"session_max_hours,omitempty"`
	// LockoutThreshold holds the value of the "lockout_threshold" field.
	LockoutThreshold int `json:"lockout_threshold,omitempty"`
	// LockoutDurationMinutes holds the value of the "lockout_duration_minutes" field.
	LockoutDurationMinutes int `json:"lockout_duration_minutes,omitempty"`
	// IPAllowlist holds the value of the "ip_allowlist" field.
	IPAllowlist []string `json:"ip_allowlist,omitempty"`
	// MfaRequiredGlobally holds the value of the "mfa_required_globally" field.
	MfaRequiredGlobally bool `json:"mfa_required_globally,omitempty"`
	// NotificationEmailEnabled holds the value of the "notification_email_enabled" field.
	NotificationEmailEnabled bool `json:"notification_email_enabled,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy string `json:"updated_by,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InstanceSettingsQuery when eager-loading is set.
	Edges        InstanceSettingsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InstanceSettingsEdges holds the relations/edges for other nodes in the graph.
type InstanceSettingsEdges struct {
	// Realm holds the value of the realm edge.
	Realm *Realm `json:"realm,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RealmOrErr returns the Realm value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InstanceSettingsEdges) RealmOrErr() (*Realm, error) {
	if e.Realm != nil {
		return e.Realm, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: realm.Label}
	}
	return nil, &NotLoadedError{edge: "realm"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InstanceSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case instancesettings.FieldIPAllowlist:
			values[i] = new([]byte)
		case instancesettings.FieldMfaRequiredGlobally, instancesettings.FieldNotificationEmailEnabled:
			values[i] = new(sql.NullBool)
		case instancesettings.FieldMinPasswordLength, instancesettings.FieldPasswordExpiryDays, instancesettings.FieldSessionIdleMinutes, instancesettings.FieldSessionMaxHours, instancesettings.FieldLockoutThreshold, instancesettings.FieldLockoutDurationMinutes:
			values[i] = new(sql.NullInt64)
		case instancesettings.FieldID, instancesettings.FieldRealmID, instancesettings.FieldManagedBy, instancesettings.FieldUpdatedBy:
			values[i] = new(sql.NullString)
		case instancesettings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InstanceSettings fields.
func (_m *InstanceSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case instancesettings.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case instancesettings.FieldRealmID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field realm_id", values[i])
			} else if value.Valid {
				_m.RealmID = value.String
			}
		case instancesettings.FieldManagedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field managed_by", values[i])
			} else if value.Valid {
				_m.ManagedBy = schema.InstanceSettingsManagedBy(value.String)
			}
		case instancesettings.FieldMinPasswordLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_password_length", values[i])
			} else if value.Valid {
				_m.MinPasswordLength = int(value.Int64)
			}
		case instancesettings.FieldPasswordExpiryDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field password_expiry_days", values[i])
			} else if value.Valid {
				_m.PasswordExpiryDays = int(value.Int64)
			}
		case instancesettings.FieldSessionIdleMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_idle_minutes", values[i])
			} else if value.Valid {
				_m.SessionIdleMinutes = int(value.Int64)
			}
		case instancesettings.FieldSessionMaxHours:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field session_max_hours", values[i])
			} else if value.Valid {
				_m.SessionMaxHours = int(value.Int64)
			}
		case instancesettings.FieldLockoutThreshold:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lockout_threshold", values[i])
			} else if value.Valid {
				_m.LockoutThreshold = int(value.Int64)
			}
		case instancesettings.FieldLockoutDurationMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lockout_duration_minutes", values[i])
			} else if value.Valid {
				_m.LockoutDurationMinutes = int(value.Int64)
			}
		case instancesettings.FieldIPAllowlist:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ip_allowlist", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.IPAllowlist); err != nil {
					return fmt.Errorf("unmarshal field ip_allowlist: %w", err)
				}
			}
		case instancesettings.FieldMfaRequiredGlobally:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field mfa_required_globally", values[i])
			} else if value.Valid {
				_m.MfaRequiredGlobally = value.Bool
			}
		case instancesettings.FieldNotificationEmailEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field notification_email_enabled", values[i])
			} else if value.Valid {
				_m.NotificationEmailEnabled = value.Bool
			}
		case instancesettings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case instancesettings.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InstanceSettings.
// This includes values selected through modifiers, order, etc.
func (_m *InstanceSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRealm queries the "realm" edge of the InstanceSettings entity.
func (_m *InstanceSettings) QueryRealm() *RealmQuery {
	return NewInstanceSettingsClient(_m.config).QueryRealm(_m)
}

// Update returns a builder for updating this InstanceSettings.
// Note that you need to call InstanceSettings.Unwrap() before calling this method if this InstanceSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InstanceSettings) Update() *InstanceSettingsUpdateOne {
	return NewInstanceSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InstanceSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InstanceSettings) Unwrap() *InstanceSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InstanceSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InstanceSettings) String() string {
	var builder strings.Builder
	builder.WriteString("InstanceSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("realm_id=")
	builder.WriteString(_m.RealmID)
	builder.WriteString(", ")
	builder.WriteString("managed_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.ManagedBy))
	builder.WriteString(", ")
	builder.WriteString("min_password_length=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinPasswordLength))
	builder.WriteString(", ")
	builder.WriteString("password_expiry_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.PasswordExpiryDays))
	builder.WriteString(", ")
	builder.WriteString("session_idle_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionIdleMinutes))
	builder.WriteString(", ")
	builder.WriteString("session_max_hours=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionMaxHours))
	builder.WriteString(", ")
	builder.WriteString("lockout_threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.LockoutThreshold))
	builder.WriteString(", ")
	builder.WriteString("lockout_duration_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.LockoutDurationMinutes))
	builder.WriteString(", ")
	builder.WriteString("ip_allowlist=")
	builder.WriteString(fmt.Sprintf("%v", _m.IPAllowlist))
	builder.WriteString(", ")
	builder.WriteString("mfa_required_globally=")
	builder.WriteString(fmt.Sprintf("%v", _m.MfaRequiredGlobally))
	builder.WriteString(", ")
	builder.WriteString("notification_email_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotificationEmailEnabled))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteByte(')')
	return builder.String()
}

// InstanceSettingsSlice is a parsable slice of InstanceSettings.
type InstanceSettingsSlice []*InstanceSettings
