// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"sso.internal/sso/ent/instancesettings"
	"sso.internal/sso/ent/predicate"
	"sso.internal/sso/ent/schema"
)

// InstanceSettingsUpdate is the builder for updating InstanceSettings entities.
type InstanceSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *InstanceSettingsMutation
}

// Where appends a list predicates to the InstanceSettingsUpdate builder.
func (_u *InstanceSettingsUpdate) Where(ps ...predicate.InstanceSettings) *InstanceSettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetManagedBy sets the "managed_by" field.
func (_u *InstanceSettingsUpdate) SetManagedBy(v schema.InstanceSettingsManagedBy) *InstanceSettingsUpdate {
	_u.mutation.SetManagedBy(v)
	return _u
}

// SetNillableManagedBy sets the "managed_by" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillableManagedBy(v *schema.InstanceSettingsManagedBy) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetManagedBy(*v)
	}
	return _u
}

// SetMinPasswordLength sets the "min_password_length" field.
func (_u *InstanceSettingsUpdate) SetMinPasswordLength(v int) *InstanceSettingsUpdate {
	_u.mutation.ResetMinPasswordLength()
	_u.mutation.SetMinPasswordLength(v)
	return _u
}

// SetNillableMinPasswordLength sets the "min_password_length" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillableMinPasswordLength(v *int) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetMinPasswordLength(*v)
	}
	return _u
}

// AddMinPasswordLength adds value to the "min_password_length" field.
func (_u *InstanceSettingsUpdate) AddMinPasswordLength(v int) *InstanceSettingsUpdate {
	_u.mutation.AddMinPasswordLength(v)
	return _u
}

// SetPasswordExpiryDays sets the "password_expiry_days" field.
func (_u *InstanceSettingsUpdate) SetPasswordExpiryDays(v int) *InstanceSettingsUpdate {
	_u.mutation.ResetPasswordExpiryDays()
	_u.mutation.SetPasswordExpiryDays(v)
	return _u
}

// SetNillablePasswordExpiryDays sets the "password_expiry_days" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillablePasswordExpiryDays(v *int) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetPasswordExpiryDays(*v)
	}
	return _u
}

// AddPasswordExpiryDays adds value to the "password_expiry_days" field.
func (_u *InstanceSettingsUpdate) AddPasswordExpiryDays(v int) *InstanceSettingsUpdate {
	_u.mutation.AddPasswordExpiryDays(v)
	return _u
}

// SetSessionIdleMinutes sets the "session_idle_minutes" field.
func (_u *InstanceSettingsUpdate) SetSessionIdleMinutes(v int) *InstanceSettingsUpdate {
	_u.mutation.ResetSessionIdleMinutes()
	_u.mutation.SetSessionIdleMinutes(v)
	return _u
}

// SetNillableSessionIdleMinutes sets the "session_idle_minutes" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillableSessionIdleMinutes(v *int) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetSessionIdleMinutes(*v)
	}
	return _u
}

// AddSessionIdleMinutes adds value to the "session_idle_minutes" field.
func (_u *InstanceSettingsUpdate) AddSessionIdleMinutes(v int) *InstanceSettingsUpdate {
	_u.mutation.AddSessionIdleMinutes(v)
	return _u
}

// SetSessionMaxHours sets the "session_max_hours" field.
func (_u *InstanceSettingsUpdate) SetSessionMaxHours(v int) *InstanceSettingsUpdate {
	_u.mutation.ResetSessionMaxHours()
	_u.mutation.SetSessionMaxHours(v)
	return _u
}

// SetNillableSessionMaxHours sets the "session_max_hours" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillableSessionMaxHours(v *int) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetSessionMaxHours(*v)
	}
	return _u
}

// AddSessionMaxHours adds value to the "session_max_hours" field.
func (_u *InstanceSettingsUpdate) AddSessionMaxHours(v int) *InstanceSettingsUpdate {
	_u.mutation.AddSessionMaxHours(v)
	return _u
}

// SetLockoutThreshold sets the "lockout_threshold" field.
func (_u *InstanceSettingsUpdate) SetLockoutThreshold(v int) *InstanceSettingsUpdate {
	_u.mutation.ResetLockoutThreshold()
	_u.mutation.SetLockoutThreshold(v)
	return _u
}

// SetNillableLockoutThreshold sets the "lockout_threshold" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillableLockoutThreshold(v *int) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetLockoutThreshold(*v)
	}
	return _u
}

// AddLockoutThreshold adds value to the "lockout_threshold" field.
func (_u *InstanceSettingsUpdate) AddLockoutThreshold(v int) *InstanceSettingsUpdate {
	_u.mutation.AddLockoutThreshold(v)
	return _u
}

// SetLockoutDurationMinutes sets the "lockout_duration_minutes" field.
func (_u *InstanceSettingsUpdate) SetLockoutDurationMinutes(v int) *InstanceSettingsUpdate {
	_u.mutation.ResetLockoutDurationMinutes()
	_u.mutation.SetLockoutDurationMinutes(v)
	return _u
}

// SetNillableLockoutDurationMinutes sets the "lockout_duration_minutes" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillableLockoutDurationMinutes(v *int) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetLockoutDurationMinutes(*v)
	}
	return _u
}

// AddLockoutDurationMinutes adds value to the "lockout_duration_minutes" field.
func (_u *InstanceSettingsUpdate) AddLockoutDurationMinutes(v int) *InstanceSettingsUpdate {
	_u.mutation.AddLockoutDurationMinutes(v)
	return _u
}

// SetIPAllowlist sets the "ip_allowlist" field.
func (_u *InstanceSettingsUpdate) SetIPAllowlist(v []string) *InstanceSettingsUpdate {
	_u.mutation.SetIPAllowlist(v)
	return _u
}

// AppendIPAllowlist appends value to the "ip_allowlist" field.
func (_u *InstanceSettingsUpdate) AppendIPAllowlist(v []string) *InstanceSettingsUpdate {
	_u.mutation.AppendIPAllowlist(v)
	return _u
}

// ClearIPAllowlist clears the value of the "ip_allowlist" field.
func (_u *InstanceSettingsUpdate) ClearIPAllowlist() *InstanceSettingsUpdate {
	_u.mutation.ClearIPAllowlist()
	return _u
}

// SetMfaRequiredGlobally sets the "mfa_required_globally" field.
func (_u *InstanceSettingsUpdate) SetMfaRequiredGlobally(v bool) *InstanceSettingsUpdate {
	_u.mutation.SetMfaRequiredGlobally(v)
	return _u
}

// SetNillableMfaRequiredGlobally sets the "mfa_required_globally" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillableMfaRequiredGlobally(v *bool) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetMfaRequiredGlobally(*v)
	}
	return _u
}

// SetNotificationEmailEnabled sets the "notification_email_enabled" field.
func (_u *InstanceSettingsUpdate) SetNotificationEmailEnabled(v bool) *InstanceSettingsUpdate {
	_u.mutation.SetNotificationEmailEnabled(v)
	return _u
}

// SetNillableNotificationEmailEnabled sets the "notification_email_enabled" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillableNotificationEmailEnabled(v *bool) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetNotificationEmailEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InstanceSettingsUpdate) SetUpdatedAt(v time.Time) *InstanceSettingsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *InstanceSettingsUpdate) SetUpdatedBy(v string) *InstanceSettingsUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *InstanceSettingsUpdate) SetNillableUpdatedBy(v *string) *InstanceSettingsUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *InstanceSettingsUpdate) ClearUpdatedBy() *InstanceSettingsUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the InstanceSettingsMutation object of the builder.
func (_u *InstanceSettingsUpdate) Mutation() *InstanceSettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InstanceSettingsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InstanceSettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceSettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InstanceSettingsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := instancesettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstanceSettingsUpdate) check() error {
	if _u.mutation.RealmCleared() && len(_u.mutation.RealmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InstanceSettings.realm"`)
	}
	return nil
}

func (_u *InstanceSettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instancesettings.Table, instancesettings.Columns, sqlgraph.NewFieldSpec(instancesettings.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ManagedBy(); ok {
		_spec.SetField(instancesettings.FieldManagedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinPasswordLength(); ok {
		_spec.SetField(instancesettings.FieldMinPasswordLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinPasswordLength(); ok {
		_spec.AddField(instancesettings.FieldMinPasswordLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PasswordExpiryDays(); ok {
		_spec.SetField(instancesettings.FieldPasswordExpiryDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPasswordExpiryDays(); ok {
		_spec.AddField(instancesettings.FieldPasswordExpiryDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SessionIdleMinutes(); ok {
		_spec.SetField(instancesettings.FieldSessionIdleMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionIdleMinutes(); ok {
		_spec.AddField(instancesettings.FieldSessionIdleMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SessionMaxHours(); ok {
		_spec.SetField(instancesettings.FieldSessionMaxHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionMaxHours(); ok {
		_spec.AddField(instancesettings.FieldSessionMaxHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LockoutThreshold(); ok {
		_spec.SetField(instancesettings.FieldLockoutThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLockoutThreshold(); ok {
		_spec.AddField(instancesettings.FieldLockoutThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LockoutDurationMinutes(); ok {
		_spec.SetField(instancesettings.FieldLockoutDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLockoutDurationMinutes(); ok {
		_spec.AddField(instancesettings.FieldLockoutDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IPAllowlist(); ok {
		_spec.SetField(instancesettings.FieldIPAllowlist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAllowlist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, instancesettings.FieldIPAllowlist, value)
		})
	}
	if _u.mutation.IPAllowlistCleared() {
		_spec.ClearField(instancesettings.FieldIPAllowlist, field.TypeJSON)
	}
	if value, ok := _u.mutation.MfaRequiredGlobally(); ok {
		_spec.SetField(instancesettings.FieldMfaRequiredGlobally, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotificationEmailEnabled(); ok {
		_spec.SetField(instancesettings.FieldNotificationEmailEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(instancesettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(instancesettings.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(instancesettings.FieldUpdatedBy, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instancesettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InstanceSettingsUpdateOne is the builder for updating a single InstanceSettings entity.
type InstanceSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InstanceSettingsMutation
}

// SetManagedBy sets the "managed_by" field.
func (_u *InstanceSettingsUpdateOne) SetManagedBy(v schema.InstanceSettingsManagedBy) *InstanceSettingsUpdateOne {
	_u.mutation.SetManagedBy(v)
	return _u
}

// SetNillableManagedBy sets the "managed_by" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillableManagedBy(v *schema.InstanceSettingsManagedBy) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetManagedBy(*v)
	}
	return _u
}

// SetMinPasswordLength sets the "min_password_length" field.
func (_u *InstanceSettingsUpdateOne) SetMinPasswordLength(v int) *InstanceSettingsUpdateOne {
	_u.mutation.ResetMinPasswordLength()
	_u.mutation.SetMinPasswordLength(v)
	return _u
}

// SetNillableMinPasswordLength sets the "min_password_length" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillableMinPasswordLength(v *int) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetMinPasswordLength(*v)
	}
	return _u
}

// AddMinPasswordLength adds value to the "min_password_length" field.
func (_u *InstanceSettingsUpdateOne) AddMinPasswordLength(v int) *InstanceSettingsUpdateOne {
	_u.mutation.AddMinPasswordLength(v)
	return _u
}

// SetPasswordExpiryDays sets the "password_expiry_days" field.
func (_u *InstanceSettingsUpdateOne) SetPasswordExpiryDays(v int) *InstanceSettingsUpdateOne {
	_u.mutation.ResetPasswordExpiryDays()
	_u.mutation.SetPasswordExpiryDays(v)
	return _u
}

// SetNillablePasswordExpiryDays sets the "password_expiry_days" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillablePasswordExpiryDays(v *int) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetPasswordExpiryDays(*v)
	}
	return _u
}

// AddPasswordExpiryDays adds value to the "password_expiry_days" field.
func (_u *InstanceSettingsUpdateOne) AddPasswordExpiryDays(v int) *InstanceSettingsUpdateOne {
	_u.mutation.AddPasswordExpiryDays(v)
	return _u
}

// SetSessionIdleMinutes sets the "session_idle_minutes" field.
func (_u *InstanceSettingsUpdateOne) SetSessionIdleMinutes(v int) *InstanceSettingsUpdateOne {
	_u.mutation.ResetSessionIdleMinutes()
	_u.mutation.SetSessionIdleMinutes(v)
	return _u
}

// SetNillableSessionIdleMinutes sets the "session_idle_minutes" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillableSessionIdleMinutes(v *int) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetSessionIdleMinutes(*v)
	}
	return _u
}

// AddSessionIdleMinutes adds value to the "session_idle_minutes" field.
func (_u *InstanceSettingsUpdateOne) AddSessionIdleMinutes(v int) *InstanceSettingsUpdateOne {
	_u.mutation.AddSessionIdleMinutes(v)
	return _u
}

// SetSessionMaxHours sets the "session_max_hours" field.
func (_u *InstanceSettingsUpdateOne) SetSessionMaxHours(v int) *InstanceSettingsUpdateOne {
	_u.mutation.ResetSessionMaxHours()
	_u.mutation.SetSessionMaxHours(v)
	return _u
}

// SetNillableSessionMaxHours sets the "session_max_hours" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillableSessionMaxHours(v *int) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetSessionMaxHours(*v)
	}
	return _u
}

// AddSessionMaxHours adds value to the "session_max_hours" field.
func (_u *InstanceSettingsUpdateOne) AddSessionMaxHours(v int) *InstanceSettingsUpdateOne {
	_u.mutation.AddSessionMaxHours(v)
	return _u
}

// SetLockoutThreshold sets the "lockout_threshold" field.
func (_u *InstanceSettingsUpdateOne) SetLockoutThreshold(v int) *InstanceSettingsUpdateOne {
	_u.mutation.ResetLockoutThreshold()
	_u.mutation.SetLockoutThreshold(v)
	return _u
}

// SetNillableLockoutThreshold sets the "lockout_threshold" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillableLockoutThreshold(v *int) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetLockoutThreshold(*v)
	}
	return _u
}

// AddLockoutThreshold adds value to the "lockout_threshold" field.
func (_u *InstanceSettingsUpdateOne) AddLockoutThreshold(v int) *InstanceSettingsUpdateOne {
	_u.mutation.AddLockoutThreshold(v)
	return _u
}

// SetLockoutDurationMinutes sets the "lockout_duration_minutes" field.
func (_u *InstanceSettingsUpdateOne) SetLockoutDurationMinutes(v int) *InstanceSettingsUpdateOne {
	_u.mutation.ResetLockoutDurationMinutes()
	_u.mutation.SetLockoutDurationMinutes(v)
	return _u
}

// SetNillableLockoutDurationMinutes sets the "lockout_duration_minutes" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillableLockoutDurationMinutes(v *int) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetLockoutDurationMinutes(*v)
	}
	return _u
}

// AddLockoutDurationMinutes adds value to the "lockout_duration_minutes" field.
func (_u *InstanceSettingsUpdateOne) AddLockoutDurationMinutes(v int) *InstanceSettingsUpdateOne {
	_u.mutation.AddLockoutDurationMinutes(v)
	return _u
}

// SetIPAllowlist sets the "ip_allowlist" field.
func (_u *InstanceSettingsUpdateOne) SetIPAllowlist(v []string) *InstanceSettingsUpdateOne {
	_u.mutation.SetIPAllowlist(v)
	return _u
}

// AppendIPAllowlist appends value to the "ip_allowlist" field.
func (_u *InstanceSettingsUpdateOne) AppendIPAllowlist(v []string) *InstanceSettingsUpdateOne {
	_u.mutation.AppendIPAllowlist(v)
	return _u
}

// ClearIPAllowlist clears the value of the "ip_allowlist" field.
func (_u *InstanceSettingsUpdateOne) ClearIPAllowlist() *InstanceSettingsUpdateOne {
	_u.mutation.ClearIPAllowlist()
	return _u
}

// SetMfaRequiredGlobally sets the "mfa_required_globally" field.
func (_u *InstanceSettingsUpdateOne) SetMfaRequiredGlobally(v bool) *InstanceSettingsUpdateOne {
	_u.mutation.SetMfaRequiredGlobally(v)
	return _u
}

// SetNillableMfaRequiredGlobally sets the "mfa_required_globally" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillableMfaRequiredGlobally(v *bool) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetMfaRequiredGlobally(*v)
	}
	return _u
}

// SetNotificationEmailEnabled sets the "notification_email_enabled" field.
func (_u *InstanceSettingsUpdateOne) SetNotificationEmailEnabled(v bool) *InstanceSettingsUpdateOne {
	_u.mutation.SetNotificationEmailEnabled(v)
	return _u
}

// SetNillableNotificationEmailEnabled sets the "notification_email_enabled" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillableNotificationEmailEnabled(v *bool) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetNotificationEmailEnabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InstanceSettingsUpdateOne) SetUpdatedAt(v time.Time) *InstanceSettingsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *InstanceSettingsUpdateOne) SetUpdatedBy(v string) *InstanceSettingsUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *InstanceSettingsUpdateOne) SetNillableUpdatedBy(v *string) *InstanceSettingsUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *InstanceSettingsUpdateOne) ClearUpdatedBy() *InstanceSettingsUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the InstanceSettingsMutation object of the builder.
func (_u *InstanceSettingsUpdateOne) Mutation() *InstanceSettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the InstanceSettingsUpdate builder.
func (_u *InstanceSettingsUpdateOne) Where(ps ...predicate.InstanceSettings) *InstanceSettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InstanceSettingsUpdateOne) Select(field string, fields ...string) *InstanceSettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InstanceSettings entity.
func (_u *InstanceSettingsUpdateOne) Save(ctx context.Context) (*InstanceSettings, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceSettingsUpdateOne) SaveX(ctx context.Context) *InstanceSettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InstanceSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InstanceSettingsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := instancesettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstanceSettingsUpdateOne) check() error {
	if _u.mutation.RealmCleared() && len(_u.mutation.RealmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "InstanceSettings.realm"`)
	}
	return nil
}

func (_u *InstanceSettingsUpdateOne) sqlSave(ctx context.Context) (_node *InstanceSettings, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instancesettings.Table, instancesettings.Columns, sqlgraph.NewFieldSpec(instancesettings.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InstanceSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instancesettings.FieldID)
		for _, f := range fields {
			if !instancesettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != instancesettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ManagedBy(); ok {
		_spec.SetField(instancesettings.FieldManagedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.MinPasswordLength(); ok {
		_spec.SetField(instancesettings.FieldMinPasswordLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinPasswordLength(); ok {
		_spec.AddField(instancesettings.FieldMinPasswordLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PasswordExpiryDays(); ok {
		_spec.SetField(instancesettings.FieldPasswordExpiryDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPasswordExpiryDays(); ok {
		_spec.AddField(instancesettings.FieldPasswordExpiryDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SessionIdleMinutes(); ok {
		_spec.SetField(instancesettings.FieldSessionIdleMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionIdleMinutes(); ok {
		_spec.AddField(instancesettings.FieldSessionIdleMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SessionMaxHours(); ok {
		_spec.SetField(instancesettings.FieldSessionMaxHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionMaxHours(); ok {
		_spec.AddField(instancesettings.FieldSessionMaxHours, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LockoutThreshold(); ok {
		_spec.SetField(instancesettings.FieldLockoutThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLockoutThreshold(); ok {
		_spec.AddField(instancesettings.FieldLockoutThreshold, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LockoutDurationMinutes(); ok {
		_spec.SetField(instancesettings.FieldLockoutDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLockoutDurationMinutes(); ok {
		_spec.AddField(instancesettings.FieldLockoutDurationMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IPAllowlist(); ok {
		_spec.SetField(instancesettings.FieldIPAllowlist, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedIPAllowlist(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, instancesettings.FieldIPAllowlist, value)
		})
	}
	if _u.mutation.IPAllowlistCleared() {
		_spec.ClearField(instancesettings.FieldIPAllowlist, field.TypeJSON)
	}
	if value, ok := _u.mutation.MfaRequiredGlobally(); ok {
		_spec.SetField(instancesettings.FieldMfaRequiredGlobally, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NotificationEmailEnabled(); ok {
		_spec.SetField(instancesettings.FieldNotificationEmailEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(instancesettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(instancesettings.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(instancesettings.FieldUpdatedBy, field.TypeString)
	}
	_node = &InstanceSettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instancesettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
