// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"sso.internal/sso/ent/keyrotationlog"
	"sso.internal/sso/ent/predicate"
)

// KeyRotationLogDelete is the builder for deleting a KeyRotationLog entity.
type KeyRotationLogDelete struct {
	config
	hooks    []Hook
	mutation *KeyRotationLogMutation
}

// Where appends a list predicates to the KeyRotationLogDelete builder.
func (_d *KeyRotationLogDelete) Where(ps ...predicate.KeyRotationLog) *KeyRotationLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *KeyRotationLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *KeyRotationLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *KeyRotationLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(keyrotationlog.Table, sqlgraph.NewFieldSpec(keyrotationlog.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// KeyRotationLogDeleteOne is the builder for deleting a single KeyRotationLog entity.
type KeyRotationLogDeleteOne struct {
	_d *KeyRotationLogDelete
}

// Where appends a list predicates to the KeyRotationLogDelete builder.
func (_d *KeyRotationLogDeleteOne) Where(ps ...predicate.KeyRotationLog) *KeyRotationLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *KeyRotationLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{keyrotationlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *KeyRotationLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
