// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"sso.internal/sso/ent/mfamethod"
	"sso.internal/sso/ent/schema"
	"sso.internal/sso/ent/user"
)

// MfaMethod is the model entity for the MfaMethod schema.
type MfaMethod struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID string `json:"user_id,omitempty"`
	// Type holds the value of the "type" field.
	Type schema.MfaMethodType `json:"type,omitempty"`
	// SecretEncrypted holds the value of the "secret_encrypted" field.
	SecretEncrypted string `json:"secret_encrypted,omitempty"`
	// CredentialID holds the value of the "credential_id" field.
	CredentialID string `json:"credential_id,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey string `json:"public_key,omitempty"`
	// IsDiscoverable holds the value of the "is_discoverable" field.
	IsDiscoverable bool `json:"is_discoverable,omitempty"`
	// Status holds the value of the "status" field.
	Status schema.MfaMethodStatus `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LastUsedAt holds the value of the "last_used_at" field.
	LastUsedAt time.Time `json:"last_used_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MfaMethodQuery when eager-loading is set.
	Edges        MfaMethodEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MfaMethodEdges holds the relations/edges for other nodes in the graph.
type MfaMethodEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MfaMethodEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MfaMethod) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mfamethod.FieldIsDiscoverable:
			values[i] = new(sql.NullBool)
		case mfamethod.FieldID, mfamethod.FieldUserID, mfamethod.FieldType, mfamethod.FieldSecretEncrypted, mfamethod.FieldCredentialID, mfamethod.FieldPublicKey, mfamethod.FieldStatus:
			values[i] = new(sql.NullString)
		case mfamethod.FieldCreatedAt, mfamethod.FieldUpdatedAt, mfamethod.FieldLastUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MfaMethod fields.
func (_m *MfaMethod) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mfamethod.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case mfamethod.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.String
			}
		case mfamethod.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = schema.MfaMethodType(value.String)
			}
		case mfamethod.FieldSecretEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_encrypted", values[i])
			} else if value.Valid {
				_m.SecretEncrypted = value.String
			}
		case mfamethod.FieldCredentialID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credential_id", values[i])
			} else if value.Valid {
				_m.CredentialID = value.String
			}
		case mfamethod.FieldPublicKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value.Valid {
				_m.PublicKey = value.String
			}
		case mfamethod.FieldIsDiscoverable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_discoverable", values[i])
			} else if value.Valid {
				_m.IsDiscoverable = value.Bool
			}
		case mfamethod.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = schema.MfaMethodStatus(value.String)
			}
		case mfamethod.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mfamethod.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case mfamethod.FieldLastUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_used_at", values[i])
			} else if value.Valid {
				_m.LastUsedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MfaMethod.
// This includes values selected through modifiers, order, etc.
func (_m *MfaMethod) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the MfaMethod entity.
func (_m *MfaMethod) QueryOwner() *UserQuery {
	return NewMfaMethodClient(_m.config).QueryOwner(_m)
}

// Update returns a builder for updating this MfaMethod.
// Note that you need to call MfaMethod.Unwrap() before calling this method if this MfaMethod
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MfaMethod) Update() *MfaMethodUpdateOne {
	return NewMfaMethodClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MfaMethod entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MfaMethod) Unwrap() *MfaMethod {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MfaMethod is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MfaMethod) String() string {
	var builder strings.Builder
	builder.WriteString("MfaMethod(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(_m.UserID)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("secret_encrypted=")
	builder.WriteString(_m.SecretEncrypted)
	builder.WriteString(", ")
	builder.WriteString("credential_id=")
	builder.WriteString(_m.CredentialID)
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(_m.PublicKey)
	builder.WriteString(", ")
	builder.WriteString("is_discoverable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDiscoverable))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_used_at=")
	builder.WriteString(_m.LastUsedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MfaMethods is a parsable slice of MfaMethod.
type MfaMethods []*MfaMethod
