// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"sso.internal/sso/ent/predicate"
	"sso.internal/sso/ent/timeout"
)

// TimeoutUpdate is the builder for updating Timeout entities.
type TimeoutUpdate struct {
	config
	hooks    []Hook
	mutation *TimeoutMutation
}

// Where appends a list predicates to the TimeoutUpdate builder.
func (_u *TimeoutUpdate) Where(ps ...predicate.Timeout) *TimeoutUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *TimeoutUpdate) SetEndsAt(v time.Time) *TimeoutUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *TimeoutUpdate) SetNillableEndsAt(v *time.Time) *TimeoutUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *TimeoutUpdate) ClearEndsAt() *TimeoutUpdate {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetReason sets the "reason" field.
func (_u *TimeoutUpdate) SetReason(v string) *TimeoutUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *TimeoutUpdate) SetNillableReason(v *string) *TimeoutUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// Mutation returns the TimeoutMutation object of the builder.
func (_u *TimeoutUpdate) Mutation() *TimeoutMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TimeoutUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimeoutUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TimeoutUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimeoutUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimeoutUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := timeout.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Timeout.reason": %w`, err)}
		}
	}
	if _u.mutation.RealmCleared() && len(_u.mutation.RealmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Timeout.realm"`)
	}
	return nil
}

func (_u *TimeoutUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timeout.Table, timeout.Columns, sqlgraph.NewFieldSpec(timeout.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(timeout.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(timeout.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(timeout.FieldReason, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timeout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TimeoutUpdateOne is the builder for updating a single Timeout entity.
type TimeoutUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TimeoutMutation
}

// SetEndsAt sets the "ends_at" field.
func (_u *TimeoutUpdateOne) SetEndsAt(v time.Time) *TimeoutUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *TimeoutUpdateOne) SetNillableEndsAt(v *time.Time) *TimeoutUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// ClearEndsAt clears the value of the "ends_at" field.
func (_u *TimeoutUpdateOne) ClearEndsAt() *TimeoutUpdateOne {
	_u.mutation.ClearEndsAt()
	return _u
}

// SetReason sets the "reason" field.
func (_u *TimeoutUpdateOne) SetReason(v string) *TimeoutUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *TimeoutUpdateOne) SetNillableReason(v *string) *TimeoutUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// Mutation returns the TimeoutMutation object of the builder.
func (_u *TimeoutUpdateOne) Mutation() *TimeoutMutation {
	return _u.mutation
}

// Where appends a list predicates to the TimeoutUpdate builder.
func (_u *TimeoutUpdateOne) Where(ps ...predicate.Timeout) *TimeoutUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TimeoutUpdateOne) Select(field string, fields ...string) *TimeoutUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Timeout entity.
func (_u *TimeoutUpdateOne) Save(ctx context.Context) (*Timeout, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TimeoutUpdateOne) SaveX(ctx context.Context) *Timeout {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TimeoutUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TimeoutUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TimeoutUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := timeout.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Timeout.reason": %w`, err)}
		}
	}
	if _u.mutation.RealmCleared() && len(_u.mutation.RealmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Timeout.realm"`)
	}
	return nil
}

func (_u *TimeoutUpdateOne) sqlSave(ctx context.Context) (_node *Timeout, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(timeout.Table, timeout.Columns, sqlgraph.NewFieldSpec(timeout.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Timeout.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, timeout.FieldID)
		for _, f := range fields {
			if !timeout.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != timeout.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(timeout.FieldEndsAt, field.TypeTime, value)
	}
	if _u.mutation.EndsAtCleared() {
		_spec.ClearField(timeout.FieldEndsAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(timeout.FieldReason, field.TypeString, value)
	}
	_node = &Timeout{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{timeout.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
