// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"sso.internal/sso/ent/realm"
	"sso.internal/sso/ent/schema"
	"sso.internal/sso/ent/timeout"
)

// Timeout is the model entity for the Timeout schema.
type Timeout struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// RealmID holds the value of the "realm_id" field.
	RealmID string `json:"realm_id,omitempty"`
	// TargetType holds the value of the "target_type" field.
	TargetType schema.TimeoutTargetType `json:"target_type,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID string `json:"target_id,omitempty"`
	// StartsAt holds the value of the "starts_at" field.
	StartsAt time.Time `json:"starts_at,omitempty"`
	// EndsAt holds the value of the "ends_at" field.
	EndsAt time.Time `json:"ends_at,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy string `json:"created_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TimeoutQuery when eager-loading is set.
	Edges        TimeoutEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TimeoutEdges holds the relations/edges for other nodes in the graph.
type TimeoutEdges struct {
	// Realm holds the value of the realm edge.
	Realm *Realm `json:"realm,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RealmOrErr returns the Realm value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TimeoutEdges) RealmOrErr() (*Realm, error) {
	if e.Realm != nil {
		return e.Realm, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: realm.Label}
	}
	return nil, &NotLoadedError{edge: "realm"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Timeout) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case timeout.FieldID, timeout.FieldRealmID, timeout.FieldTargetType, timeout.FieldTargetID, timeout.FieldReason, timeout.FieldCreatedBy:
			values[i] = new(sql.NullString)
		case timeout.FieldStartsAt, timeout.FieldEndsAt, timeout.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Timeout fields.
func (_m *Timeout) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case timeout.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case timeout.FieldRealmID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field realm_id", values[i])
			} else if value.Valid {
				_m.RealmID = value.String
			}
		case timeout.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = schema.TimeoutTargetType(value.String)
			}
		case timeout.FieldTargetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = value.String
			}
		case timeout.FieldStartsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field starts_at", values[i])
			} else if value.Valid {
				_m.StartsAt = value.Time
			}
		case timeout.FieldEndsAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field ends_at", values[i])
			} else if value.Valid {
				_m.EndsAt = value.Time
			}
		case timeout.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case timeout.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case timeout.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Timeout.
// This includes values selected through modifiers, order, etc.
func (_m *Timeout) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRealm queries the "realm" edge of the Timeout entity.
func (_m *Timeout) QueryRealm() *RealmQuery {
	return NewTimeoutClient(_m.config).QueryRealm(_m)
}

// Update returns a builder for updating this Timeout.
// Note that you need to call Timeout.Unwrap() before calling this method if this Timeout
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Timeout) Update() *TimeoutUpdateOne {
	return NewTimeoutClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Timeout entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Timeout) Unwrap() *Timeout {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Timeout is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Timeout) String() string {
	var builder strings.Builder
	builder.WriteString("Timeout(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("realm_id=")
	builder.WriteString(_m.RealmID)
	builder.WriteString(", ")
	builder.WriteString("target_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetType))
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(_m.TargetID)
	builder.WriteString(", ")
	builder.WriteString("starts_at=")
	builder.WriteString(_m.StartsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("ends_at=")
	builder.WriteString(_m.EndsAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Timeouts is a parsable slice of Timeout.
type Timeouts []*Timeout
