// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// ClientApp is the predicate function for clientapp builders.
type ClientApp func(*sql.Selector)

// ClientGroup is the predicate function for clientgroup builders.
type ClientGroup func(*sql.Selector)

// ClientRole is the predicate function for clientrole builders.
type ClientRole func(*sql.Selector)

// ClientScope is the predicate function for clientscope builders.
type ClientScope func(*sql.Selector)

// ClientScopeMapping is the predicate function for clientscopemapping builders.
type ClientScopeMapping func(*sql.Selector)

// Consent is the predicate function for consent builders.
type Consent func(*sql.Selector)

// FederatedIdentity is the predicate function for federatedidentity builders.
type FederatedIdentity func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupClientScope is the predicate function for groupclientscope builders.
type GroupClientScope func(*sql.Selector)

// IdentityProvider is the predicate function for identityprovider builders.
type IdentityProvider func(*sql.Selector)

// InstanceSettings is the predicate function for instancesettings builders.
type InstanceSettings func(*sql.Selector)

// KeyRotationLog is the predicate function for keyrotationlog builders.
type KeyRotationLog func(*sql.Selector)

// LoginAttempt is the predicate function for loginattempt builders.
type LoginAttempt func(*sql.Selector)

// MfaBackupCode is the predicate function for mfabackupcode builders.
type MfaBackupCode func(*sql.Selector)

// MfaMethod is the predicate function for mfamethod builders.
type MfaMethod func(*sql.Selector)

// PasswordResetToken is the predicate function for passwordresettoken builders.
type PasswordResetToken func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Realm is the predicate function for realm builders.
type Realm func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RoleClientScope is the predicate function for roleclientscope builders.
type RoleClientScope func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// SigningKey is the predicate function for signingkey builders.
type SigningKey func(*sql.Selector)

// Timeout is the predicate function for timeout builders.
type Timeout func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
